// Drama — données du dashboard
// Source de vérité : ROADMAP.md du repo teiki5320/drama
// Toute modification ici doit refléter une mise à jour du ROADMAP.

const RAW_BASE = 'https://raw.githubusercontent.com/teiki5320/drama/main/Drama.swiftpm/Sources/AppModule/ressources/';

// ----- Lore figé (NE PAS MODIFIER sans mettre à jour ROADMAP.md) -----
const LORE = {
  pitch: "Drama — jeu narratif iPhone/iPad. Le joueur incarne Shen Miao, jeune femme asiatique de 24 ans qui s'installe en Europe en 2026 pour son master + stage chez Lu Europe, et qui découvrira que la famille Lu a fait tuer son père en 2007.",
  format: { semaines: 208, ans: 4, scenesParSemaine: 1 },
  saisons: [
    { id: 1, label: 'Saison 1 — Arrivée et installation', range: 'W1-52', model: 'Gratuite' },
    { id: 2, label: 'Saison 2 — Fin du master + ascension', range: 'W53-104', model: 'Payante' },
    { id: 3, label: 'Saison 3 — Vie pro + révélations', range: 'W105-156', model: 'Payante' },
    { id: 4, label: 'Saison 4 — Endgame', range: 'W157-208', model: 'Payante' }
  ],
  faitsFiges: [
    { annee: 2002, fait: 'Naissance de Shen Miao au village' },
    { annee: 2007, fait: 'Shen Liwei (papa, 38 ans, comptable Groupe Lu) refuse une promotion → tué dans un faux accident de moto' },
    { annee: 2014, fait: 'Lu Senior (grand-père, fondateur, intercepteur de la lettre du papa) meurt de vieillesse. Lu Mingzhe (fils) prend le pouvoir.' },
    { annee: 2014, fait: 'Lu Huan (14 ans) apprend que son père « a fait quelque chose »' },
    { annee: 2018, fait: 'Lu Mingzhe (vrai commanditaire) meurt d\'AVC' },
    { annee: 2020, fait: 'Lin (cousine, 22 ans) disparaît après être partie en Europe' },
    { annee: 2026, fait: 'Shen 24 ans → arrive en Europe (W1)' },
    { annee: 2030, fait: 'Shen 28 ans → fin du jeu (W208)' }
  ],
  troisLu: [
    { id: 'lu_senior', nom: 'Lu Senior', role: 'Grand-père, fondateur', etat: 'Mort de vieillesse en 2014', ingame: 'Hors d\'atteinte. Intercepteur de la lettre du papa.', warn: 'NE PAS confondre avec Lu Mingzhe.' },
    { id: 'lu_mingzhe', nom: 'Lu Mingzhe', role: 'Fils de Senior', etat: 'Mort d\'AVC en 2018', ingame: 'HORS JEU. Mais c\'est LE VRAI commanditaire du meurtre.', warn: 'NE JAMAIS le faire apparaître. Il est mort.' },
    { id: 'lu_huan', nom: 'Lu Huan', role: 'PDG actuel, héritier', etat: 'Vivant — antagoniste principal en jeu', ingame: 'Présent. PAS l\'auteur du crime, mais il sait ou soupçonne.', warn: 'C\'est lui qu\'on rencontre, pas son père.' }
  ],
  endings: [
    { id: 'ending_justice', label: 'Justice', emoji: '⚖️', desc: 'Procès médiatique', ecrit: true },
    { id: 'ending_argent', label: 'Argent', emoji: '💴', desc: 'Fortune offshore', ecrit: true },
    { id: 'ending_vengeance', label: 'Vengeance', emoji: '🗡', desc: 'Groupe Lu démoli', ecrit: true },
    { id: 'ending_paix', label: 'Paix', emoji: '🌸', desc: 'École au village', ecrit: true }
  ]
};

// ----- Personnages -----
const PERSONNAGES = [
  { id: 'shen', nom: 'Shen Miao', role: 'Protagoniste', faction: 'protagoniste', firstW: 1, lastW: 208, saisons: [1,2,3,4], desc: '24 ans en 2026, Asiatique, master + stage Lu Europe.', actif: true },
  { id: 'maman', nom: 'Maman', role: 'Mère de Shen', faction: 'famille', firstW: 1, lastW: 208, saisons: [1,2,3,4], desc: 'Au village. Voix off chaude, chitchats récurrents.', actif: true },
  { id: 'wei', nom: 'Wei', role: 'Cousin·e ami·e à NeoCity', faction: 'famille', firstW: 2, lastW: 208, saisons: [1,2,3,4], desc: 'Premier soutien IRL. Pivot du tournant S3 (W138 « Wei savait »).', actif: true },
  { id: 'tante_mei', nom: 'Tante Mei', role: 'Tante au village', faction: 'famille', firstW: 8, lastW: 208, saisons: [1,2,3,4], desc: 'Garde la mémoire du papa. Carnet, armoire bleue, révélations S3.', actif: true },
  { id: 'lu_huan', nom: 'Lu Huan', role: 'PDG Groupe Lu', faction: 'lu', firstW: 12, lastW: 208, saisons: [1,2,3,4], desc: 'Héritier. Antagoniste ambigu, devient humain à W142.', actif: true },
  { id: 'amanda', nom: 'Amanda', role: 'Collègue toxique', faction: 'lu', firstW: 12, lastW: 208, saisons: [1,2,3,4], desc: 'Pique au bureau, piège ascenseur W40, trahison W93.', actif: true },
  { id: 'hugo', nom: 'Hugo', role: 'Artiste, romance', faction: 'romance', firstW: 22, lastW: 208, saisons: [1,2,3,4], desc: 'Rencontré au café Hanami. Triangle vs Liu Wei à partir de S1 fin.', actif: true },
  { id: 'liu_wei', nom: 'Liu Wei', role: 'Du village, romance alternative', faction: 'romance', firstW: 47, lastW: 208, saisons: [1,2,3,4], desc: 'Arrive à NeoCity. Triangle avec Hugo.', actif: true },
  { id: 'lin', nom: 'Lin', role: 'Cousine disparue', faction: 'famille', firstW: 117, lastW: 208, saisons: [3,4], desc: 'Disparue 2020. Premiers messages codés W117. Révélée W145.', actif: true },
  { id: 'inconnu', nom: 'Inconnu / L.', role: 'Numéro mystère', faction: 'mystere', firstW: 5, lastW: 208, saisons: [1,2,3,4], desc: 'Skinner, pings énigmatiques. Identité révélée tard.', actif: true },
  { id: 'rh', nom: 'RH (inconnu)', role: 'Ressources humaines Lu', faction: 'lu', firstW: 13, lastW: 104, saisons: [1,2], desc: 'Mails formels, étape pression carrière.', actif: true },
  { id: 'papa', nom: 'Shen Liwei (papa)', role: 'Père de Shen, mort en 2007', faction: 'reference', firstW: null, lastW: null, saisons: [], desc: 'Hors-écran. Évoqué via carnet (W133), photos (W8, W55), souvenirs.', actif: false },
  { id: 'lu_senior', nom: 'Lu Senior', role: 'Grand-père, fondateur (†2014)', faction: 'reference', firstW: null, lastW: null, saisons: [], desc: 'Référence lore uniquement. Ne pas confondre avec Mingzhe.', actif: false },
  { id: 'lu_mingzhe', nom: 'Lu Mingzhe', role: 'Vrai commanditaire (†2018)', faction: 'reference', firstW: null, lastW: null, saisons: [], desc: 'Référence lore uniquement. HORS JEU mais c\'est LUI le coupable.', actif: false }
];

// ----- Timeline 208 semaines -----
// type : 'major' (🎯) | 'chitchat' (💬) | 'cinematic' (🌟) | 'empty' (✏)
// status : 'done' | 'todo'
// arc : id de l'arc narratif (ARCS) — émerge par juxtaposition, pas par fil coupé
const TIMELINE = [
  { w:1, season:1, title:"Arrivée NeoCity, message Maman + selfie aéroport", type:"major", contact:"maman", status:"done", sceneId:"start" , arc:"A_install" },
  { w:2, season:1, title:"Premier jour campus + stage, intro Wei", type:"major", contact:"wei", status:"done", sceneId:"wei_morning" , arc:"A_install" },
  { w:3, season:1, title:"Fais le tour du studio", type:"chitchat", contact:"wei", status:"done", sceneId:"wei_w3_prompt" , arc:"A_install" },
  { w:4, season:1, title:"Maman appelle « comment ça va »", type:"chitchat", contact:"maman", status:"done", sceneId:"chitchat_maman_w4" , arc:"A_install" },
  { w:5, season:1, title:"Inconnu : « Ne fais confiance à personne »", type:"chitchat", contact:"inconnu", status:"done", sceneId:"inconnu_w5", note:"Skinner ping existe" , arc:"A_install" },
  { w:6, season:1, title:"Wei à la cantine, confidence perso", type:"chitchat", contact:"wei", status:"done", sceneId:"wei_w6_prompt" , arc:"A_install" },
  { w:7, season:1, title:"Wei : exam jeudi", type:"chitchat", contact:"wei", status:"done", sceneId:"chitchat_wei_w7" , arc:"A_install" },
  { w:8, season:1, title:"Tante Mei : photo papa jeune", type:"empty", contact:"tante_mei", status:"done", sceneId:"tante_mei_w8" , arc:"A_install" },
  { w:9, season:1, title:"Amanda : sticker WhatsApp inattendu", type:"chitchat", contact:"amanda", status:"done", sceneId:"amanda_w9_prompt", note:"Skinner" , arc:"A_install" },
  { w:10, season:1, title:"Maman : « Ne dépense pas trop »", type:"chitchat", contact:"maman", status:"done", sceneId:"maman_w10_prompt" , arc:"A_install" },
  { w:11, season:1, title:"Wei : « Tu veux rencontrer Liu Wei ? »", type:"chitchat", contact:"wei", status:"done", sceneId:"wei_w11_liuwei" , arc:"A_install" },
  { w:12, season:1, title:"Première semaine bureau, intro Lu Huan + Amanda", type:"major", contact:"lu_huan", status:"done", sceneId:"bureau_premiere_semaine" , arc:"B_lu_intro" },
  { w:13, season:1, title:"RH : NDA à signer en 24h", type:"chitchat", contact:"rh", status:"done", sceneId:"rh_w13" , arc:"B_lu_intro" },
  { w:14, season:1, title:"Amanda pique pull du village", type:"major", contact:"amanda", status:"done", sceneId:"amanda_petite_pique" , arc:"B_lu_intro" },
  { w:15, season:1, title:"Wei : « Méfie-toi d'Amanda »", type:"chitchat", contact:"wei", status:"done", sceneId:"wei_w15" , arc:"B_lu_intro" },
  { w:16, season:1, title:"Lu Huan demande heures sup", type:"major", contact:"lu_huan", status:"done", sceneId:"lu_huan_demande_overtime" , arc:"B_lu_intro" },
  { w:17, season:1, title:"Maman : ton père aurait été fier", type:"chitchat", contact:"maman", status:"done", sceneId:"maman_w17_prompt" , arc:"B_lu_intro" },
  { w:18, season:1, title:"Tante Mei appelle (santé Maman)", type:"major", contact:"tante_mei", status:"done", sceneId:"tante_mei_appelle" , arc:"B_lu_intro" },
  { w:19, season:1, title:"Wei pleure pour son ex", type:"chitchat", contact:"wei", status:"done", sceneId:"wei_w19" , arc:"B_lu_intro" },
  { w:20, season:1, title:"Inconnu : « Hugo te suit »", type:"chitchat", contact:"inconnu", status:"done", sceneId:"skinner_w20" , arc:"B_lu_intro" },
  { w:21, season:1, title:"Lu Huan : compliment public en réunion", type:"chitchat", contact:"lu_huan", status:"done", sceneId:"lu_huan_w21" , arc:"B_lu_intro" },
  { w:22, season:1, title:"Rencontre Hugo café Hanami", type:"major", contact:"hugo", status:"done", sceneId:"hugo_apparait" , arc:"C_hugo_lu" },
  { w:23, season:1, title:"Hugo : croquis dessiné de mémoire", type:"chitchat", contact:"hugo", status:"done", sceneId:"hugo_w23" , arc:"C_hugo_lu" },
  { w:24, season:1, title:"Maman : photo du chat de la voisine", type:"chitchat", contact:"maman", status:"done", sceneId:"maman_w24_prompt" , arc:"C_hugo_lu" },
  { w:25, season:1, title:"Hugo : premier date, il commande pour toi", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w25" , arc:"C_hugo_lu" },
  { w:26, season:1, title:"Amanda : « tu vas aux RH ? » (faux concerne)", type:"chitchat", contact:"amanda", status:"done", sceneId:"amanda_w26" , arc:"C_hugo_lu" },
  { w:27, season:1, title:"Tante Mei malade — 600€", type:"major", contact:"maman", status:"done", sceneId:"tante_mei_malade" , arc:"C_hugo_lu" },
  { w:28, season:1, title:"Wei te prête de l'argent (ou pas)", type:"empty", contact:"wei", status:"done", sceneId:"wei_w28" , arc:"C_hugo_lu" },
  { w:29, season:1, title:"Lu Huan : tu veux le siège ?", type:"chitchat", contact:"lu_huan", status:"done", sceneId:"lu_huan_w29" , arc:"C_hugo_lu" },
  { w:30, season:1, title:"Carrefour pro — Lu demande signature douteuse", type:"major", contact:"lu_huan", status:"done", sceneId:"carrefour_pro" , arc:"C_hugo_lu" },
  { w:31, season:1, title:"Inconnu : « tu as bien fait » ou « tu paieras »", type:"chitchat", contact:"inconnu", status:"done", sceneId:"inconnu_w31" , arc:"D_filet" },
  { w:32, season:1, title:"Maman : nouveaux voisins au village", type:"chitchat", contact:"maman", status:"done", sceneId:"maman_w32_prompt" , arc:"D_filet" },
  { w:33, season:1, title:"Hugo te peint sans te le dire", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w33" , arc:"D_filet" },
  { w:34, season:1, title:"Hugo : tu fais quoi ce week-end", type:"chitchat", contact:"hugo", status:"done", sceneId:"chitchat_hugo_w34" , arc:"D_filet" },
  { w:35, season:1, title:"L. : « cherche dans l'armoire bleue »", type:"chitchat", contact:"inconnu", status:"done", sceneId:"inconnu_w35", note:"Skinner existe" , arc:"D_filet" },
  { w:36, season:1, title:"Wei : « rumeur sur toi à la cafet »", type:"chitchat", contact:"wei", status:"done", sceneId:"wei_w36_prompt" , arc:"D_filet" },
  { w:37, season:1, title:"Insta : tu postes photo couple Hugo", type:"empty", contact:"hugo", status:"done", sceneId:"insta_w37" , arc:"D_filet" },
  { w:38, season:1, title:"Lu Huan croise Hugo dans un café", type:"empty", contact:"lu_huan", status:"done", sceneId:"lu_huan_w38" , arc:"D_filet" },
  { w:39, season:1, title:"Tante Mei : envoie un colis", type:"chitchat", contact:"tante_mei", status:"done", sceneId:"tante_mei_w39_prompt" , arc:"D_filet" },
  { w:40, season:1, title:"Le piège — Amanda diffuse photo ascenseur", type:"major", contact:"amanda", status:"done", sceneId:"le_piege" , arc:"D_filet" },
  { w:41, season:1, title:"Wei te défend en réunion", type:"empty", contact:"wei", status:"done", sceneId:"wei_w41" , arc:"D_filet" },
  { w:42, season:1, title:"Maman : tout va bien ma fille ?", type:"chitchat", contact:"maman", status:"done", sceneId:"maman_w42_prompt" , arc:"D_filet" },
  { w:43, season:1, title:"Amanda : fausse trêve « on oublie ? »", type:"empty", contact:"amanda", status:"done", sceneId:"amanda_w43" , arc:"E_reconstr" },
  { w:44, season:1, title:"Hugo : doute amoureux « t'as changé »", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w44" , arc:"E_reconstr" },
  { w:45, season:1, title:"Lu Huan : projet Hatsune (premier nom)", type:"empty", contact:"lu_huan", status:"done", sceneId:"lu_huan_w45" , arc:"E_reconstr" },
  { w:46, season:1, title:"Inconnu : ne signe rien", type:"chitchat", contact:"inconnu", status:"done", sceneId:"inconnu_w46" , arc:"E_reconstr" },
  { w:47, season:1, title:"Liu Wei arrive du village", type:"major", contact:"liu_wei", status:"done", sceneId:"liu_wei_arrive" , arc:"E_reconstr" },
  { w:48, season:1, title:"Liu Wei : photos du village", type:"chitchat", contact:"liu_wei", status:"done", sceneId:"liu_wei_w48" , arc:"E_reconstr" },
  { w:49, season:1, title:"Première hésitation Liu Wei vs Hugo", type:"empty", contact:"shen", status:"done", sceneId:"triangle_w49" , arc:"E_reconstr" },
  { w:50, season:1, title:"Présentation grand œuvre devant comité", type:"major", contact:"lu_huan", status:"done", sceneId:"grand_oeuvre" , arc:"E_reconstr" },
  { w:51, season:1, title:"Maman : qu'est-ce que tu deviens vraiment ?", type:"empty", contact:"maman", status:"done", sceneId:"maman_w51" , arc:"E_reconstr" },
  { w:52, season:1, title:"Réveillon A1 + SMS anonyme « Tu sais ce qu'a fait ton père ? »", type:"cinematic", contact:"maman", status:"done", sceneId:"reveillon_a1" , arc:"E_reconstr" },
  { w:53, season:2, title:"Bonne année — Maman te rappelle", type:"chitchat", contact:"maman", status:"done", sceneId:"maman_w53" },
  { w:54, season:2, title:"Wei : tu rentres au village pour les vacances ?", type:"chitchat", contact:"wei", status:"done", sceneId:"wei_w54_prompt" },
  { w:55, season:2, title:"Tante Mei retrouve une photo du papa", type:"empty", contact:"tante_mei", status:"done", sceneId:"tante_mei_w55" },
  { w:56, season:2, title:"Lu Huan : promotion à venir", type:"empty", contact:"lu_huan", status:"done", sceneId:"lu_huan_w56" },
  { w:57, season:2, title:"Hugo expose en galerie", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w57" },
  { w:58, season:2, title:"Amanda : nouvelle collègue (toi en danger)", type:"chitchat", contact:"amanda", status:"done", sceneId:"amanda_w58_prompt" },
  { w:59, season:2, title:"Inconnu : prépare-toi", type:"chitchat", contact:"inconnu", status:"done", sceneId:"inconnu_w59_prompt" },
  { w:60, season:2, title:"Liu Wei demande aide carte de séjour", type:"chitchat", contact:"liu_wei", status:"done", sceneId:"liu_wei_w60_prompt" },
  { w:61, season:2, title:"Wei : couple en crise (rupture imminente)", type:"empty", contact:"wei", status:"done", sceneId:"wei_w61" },
  { w:62, season:2, title:"Maman tousse au téléphone", type:"empty", contact:"maman", status:"done", sceneId:"maman_w62" },
  { w:63, season:2, title:"Lancement produit — présentation publique", type:"major", contact:"lu_huan", status:"done", sceneId:"lancement_produit" },
  { w:64, season:2, title:"Lendemain — médias en parlent", type:"empty", contact:"shen", status:"done", sceneId:"post_lancement_w64" },
  { w:65, season:2, title:"Hugo te dit qu'il t'aime", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w65" },
  { w:66, season:2, title:"Wei craque sous pression parents", type:"empty", contact:"wei", status:"done", sceneId:"wei_w66" },
  { w:67, season:2, title:"Tante Mei : viens me voir cet été", type:"empty", contact:"tante_mei", status:"done", sceneId:"tante_mei_w67_prompt" },
  { w:68, season:2, title:"Lu Huan : voyage Singapour — tu viens ?", type:"empty", contact:"lu_huan", status:"done", sceneId:"lu_huan_w68" },
  { w:69, season:2, title:"Liu Wei : on devrait parler", type:"empty", contact:"liu_wei", status:"done", sceneId:"liu_wei_w69" },
  { w:70, season:2, title:"Tu trouves un carnet de notes du papa", type:"empty", contact:"shen", status:"done", sceneId:"carnet_w70" },
  { w:71, season:2, title:"Maman : rumeurs au village", type:"chitchat", contact:"maman", status:"done", sceneId:"maman_w71_prompt" },
  { w:72, season:2, title:"Amanda : champagne à la fin du trimestre", type:"empty", contact:"amanda", status:"done", sceneId:"amanda_w72" },
  { w:73, season:2, title:"Crise Lu Huan — board veut le débarquer", type:"major", contact:"lu_huan", status:"done", sceneId:"crise_lu_huan" },
  { w:74, season:2, title:"Wei panique à propos du job", type:"empty", contact:"wei", status:"done", sceneId:"wei_w74" },
  { w:75, season:2, title:"Hugo doute : tu as changé", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w75" },
  { w:76, season:2, title:"Inconnu : 14 mars 2007", type:"chitchat", contact:"inconnu", status:"done", sceneId:"inconnu_w76_prompt" },
  { w:77, season:2, title:"Hugo t'invite à Florence", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w77" },
  { w:78, season:2, title:"Tante Mei envoie carnet papa par poste", type:"empty", contact:"tante_mei", status:"done", sceneId:"tante_mei_w78" },
  { w:79, season:2, title:"Maman : reviens un week-end", type:"chitchat", contact:"maman", status:"done", sceneId:"maman_w79_prompt" },
  { w:80, season:2, title:"Lu Huan te confie une tâche secrète", type:"empty", contact:"lu_huan", status:"done", sceneId:"lu_huan_w80" },
  { w:81, season:2, title:"Liu Wei : retour au village pour grand-mère", type:"empty", contact:"liu_wei", status:"done", sceneId:"liu_wei_w81" },
  { w:82, season:2, title:"Amanda : invitation soirée gala", type:"empty", contact:"amanda", status:"done", sceneId:"amanda_w82" },
  { w:83, season:2, title:"Tuyau bourse Lu Huan", type:"major", contact:"lu_huan", status:"done", sceneId:"opportunite_invest" },
  { w:84, season:2, title:"L. : c'est un délit d'initié", type:"chitchat", contact:"inconnu", status:"done", sceneId:"inconnu_w84_prompt" },
  { w:85, season:2, title:"Wei : bilan trim, rénovation projet", type:"chitchat", contact:"wei", status:"done", sceneId:"wei_w85_prompt" },
  { w:86, season:2, title:"Premier mois sans découvert", type:"chitchat", contact:"shen", status:"done", sceneId:"milestone_w86" },
  { w:87, season:2, title:"Tante Mei : photo arrivée colis", type:"chitchat", contact:"tante_mei", status:"done", sceneId:"tante_mei_w87_prompt" },
  { w:88, season:2, title:"Hugo : tu es prête pour Florence ?", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w88" },
  { w:89, season:2, title:"Maman : nouvelle photo de Lin enfant", type:"empty", contact:"maman", status:"done", sceneId:"maman_w89" },
  { w:90, season:2, title:"Soirée gala Lu, première fois en robe pro", type:"empty", contact:"shen", status:"done", sceneId:"gala_w90" },
  { w:91, season:2, title:"Amanda : compliment piégé", type:"chitchat", contact:"amanda", status:"done", sceneId:"amanda_w91_prompt" },
  { w:92, season:2, title:"Lu Huan : vous ressemblez à quelqu'un", type:"empty", contact:"lu_huan", status:"done", sceneId:"lu_huan_w92" },
  { w:93, season:2, title:"Trahison Amanda — RH étudient anomalies", type:"major", contact:"amanda", status:"done", sceneId:"trahison_a2" },
  { w:94, season:2, title:"Wei te défend devant les RH", type:"empty", contact:"wei", status:"done", sceneId:"wei_w94" },
  { w:95, season:2, title:"Hugo : les choses se compliquent ?", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w95" },
  { w:96, season:2, title:"Tante Mei : santé qui décline", type:"empty", contact:"tante_mei", status:"done", sceneId:"tante_mei_w96" },
  { w:97, season:2, title:"Liu Wei : on rentre tous les deux ?", type:"empty", contact:"liu_wei", status:"done", sceneId:"liu_wei_w97" },
  { w:98, season:2, title:"Maman : prends soin de toi", type:"chitchat", contact:"maman", status:"done", sceneId:"maman_w98_prompt" },
  { w:99, season:2, title:"Lu Huan : restez après la réunion", type:"chitchat", contact:"lu_huan", status:"done", sceneId:"lu_huan_w99", note:"Skinner" },
  { w:100, season:2, title:"Soutenance master", type:"empty", contact:"shen", status:"done", sceneId:"soutenance_w100" },
  { w:101, season:2, title:"Wei : on fête ça", type:"empty", contact:"wei", status:"done", sceneId:"wei_w101" },
  { w:102, season:2, title:"Inconnu : ce n'est qu'un début", type:"chitchat", contact:"inconnu", status:"done", sceneId:"inconnu_w102_prompt" },
  { w:103, season:2, title:"Climax A2 — choix carrière 3 voies", type:"major", contact:"lu_huan", status:"done", sceneId:"climax_a2" },
  { w:104, season:2, title:"Réveillon A2", type:"cinematic", contact:"maman", status:"done", sceneId:"reveillon_a2" },
  { w:105, season:3, title:"Premier mois en CDD/poste pro", type:"empty", contact:"lu_huan", status:"done", sceneId:"lu_huan_w105" },
  { w:106, season:3, title:"Hugo : il fait froid sans toi", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w106" },
  { w:107, season:3, title:"Wei te demande tuyau pro", type:"chitchat", contact:"wei", status:"done", sceneId:"wei_w107_prompt" },
  { w:108, season:3, title:"Tante Mei : carnet est dans le coffre du salon", type:"empty", contact:"tante_mei", status:"done", sceneId:"tante_mei_w108" },
  { w:109, season:3, title:"Amanda : retour discret", type:"chitchat", contact:"amanda", status:"done", sceneId:"amanda_w109_prompt" },
  { w:110, season:3, title:"Hugo dit qu'il t'aime (à toi de répondre)", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w110" },
  { w:111, season:3, title:"Maman : ton père aurait dit quoi ?", type:"empty", contact:"maman", status:"done", sceneId:"maman_w111" },
  { w:112, season:3, title:"Lu Huan : on parle bonus", type:"empty", contact:"lu_huan", status:"done", sceneId:"lu_huan_w112" },
  { w:113, season:3, title:"Promotion + clause de loyauté", type:"major", contact:"lu_huan", status:"done", sceneId:"promotion_a3" },
  { w:114, season:3, title:"Wei : promo aussi de son côté", type:"chitchat", contact:"wei", status:"done", sceneId:"wei_w114_prompt" },
  { w:115, season:3, title:"Hugo : on prend un appart ?", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w115" },
  { w:116, season:3, title:"Liu Wei : nouvelles du village", type:"chitchat", contact:"liu_wei", status:"done", sceneId:"liu_wei_w116_prompt" },
  { w:117, season:3, title:"Lin envoie premier message codé", type:"empty", contact:"inconnu", status:"done", sceneId:"lin_w117" },
  { w:118, season:3, title:"Maman : photo Mahjong Tante Mei", type:"chitchat", contact:"maman", status:"done", sceneId:"maman_w118_prompt" },
  { w:119, season:3, title:"Amanda : tente une réconciliation utile", type:"empty", contact:"amanda", status:"done", sceneId:"amanda_w119" },
  { w:120, season:3, title:"Tante Mei envoie photo armoire bleue", type:"empty", contact:"tante_mei", status:"done", sceneId:"tante_mei_w120" },
  { w:121, season:3, title:"Lu Huan : suis-moi à un dîner privé", type:"empty", contact:"lu_huan", status:"done", sceneId:"lu_huan_w121" },
  { w:122, season:3, title:"Hugo : il faut qu'on parle", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w122" },
  { w:123, season:3, title:"Passé révélé — copie registre Lu Senior", type:"major", contact:"inconnu", status:"done", sceneId:"passe_revele" },
  { w:124, season:3, title:"Wei : « je peux t'aider »", type:"empty", contact:"wei", status:"done", sceneId:"wei_w124" },
  { w:125, season:3, title:"Maman : tu m'inquiètes ma fille", type:"chitchat", contact:"maman", status:"done", sceneId:"maman_w125_prompt" },
  { w:126, season:3, title:"Wei propose de t'aider à fouiller", type:"empty", contact:"wei", status:"done", sceneId:"wei_w126" },
  { w:127, season:3, title:"Lu Huan : pourquoi cette froideur ?", type:"empty", contact:"lu_huan", status:"done", sceneId:"lu_huan_w127" },
  { w:128, season:3, title:"Tante Mei révèle papa lié au Groupe Lu", type:"major", contact:"tante_mei", status:"done", sceneId:"tante_mei_revele_papa" },
  { w:129, season:3, title:"Inconnu : courage", type:"chitchat", contact:"inconnu", status:"done", sceneId:"inconnu_w129_prompt" },
  { w:130, season:3, title:"Liu Wei retourne au village (deuil)", type:"empty", contact:"liu_wei", status:"done", sceneId:"liu_wei_w130" },
  { w:131, season:3, title:"Hugo : tu deviens distante", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w131" },
  { w:132, season:3, title:"Maman : viens me voir au village", type:"empty", contact:"maman", status:"done", sceneId:"maman_w132" },
  { w:133, season:3, title:"Vieux carnet du papa retrouvé", type:"major", contact:"shen", status:"done", sceneId:"vieux_carnet_papa" },
  { w:134, season:3, title:"Wei : qu'est-ce que t'a appris le carnet ?", type:"empty", contact:"wei", status:"done", sceneId:"wei_w134" },
  { w:135, season:3, title:"Lu Huan : projet européen confidentiel", type:"empty", contact:"lu_huan", status:"done", sceneId:"lu_huan_w135" },
  { w:136, season:3, title:"Amanda : information à monnayer", type:"empty", contact:"amanda", status:"done", sceneId:"amanda_w136" },
  { w:137, season:3, title:"Inconnu : Mingzhe", type:"chitchat", contact:"inconnu", status:"done", sceneId:"inconnu_w137_prompt", note:"Skinner" },
  { w:138, season:3, title:"Wei savait quelque chose", type:"major", contact:"wei", status:"done", sceneId:"wei_savait_quelque_chose" },
  { w:139, season:3, title:"Hugo : on prend une pause ?", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w139" },
  { w:140, season:3, title:"Tante Mei : courage ma puce", type:"chitchat", contact:"tante_mei", status:"done", sceneId:"tante_mei_w140_prompt" },
  { w:141, season:3, title:"Liu Wei : retour à NeoCity", type:"empty", contact:"liu_wei", status:"done", sceneId:"liu_wei_w141" },
  { w:142, season:3, title:"Lu Huan craque, premier moment humain", type:"major", contact:"lu_huan", status:"done", sceneId:"lu_huan_humain" },
  { w:143, season:3, title:"Maman : dis-moi tout", type:"empty", contact:"maman", status:"done", sceneId:"maman_w143" },
  { w:144, season:3, title:"Pavillon Lu, dossier Hatsune découvert", type:"major", contact:"lu_huan", status:"done", sceneId:"pavillon_lu_revele" },
  { w:145, season:3, title:"Lin révélée = ta cousine", type:"major", contact:"lin", status:"done", sceneId:"lin_revele" },
  { w:146, season:3, title:"Wei : prends soin de toi", type:"chitchat", contact:"wei", status:"done", sceneId:"wei_w146_prompt" },
  { w:147, season:3, title:"Lu Huan : silence radio", type:"empty", contact:"lu_huan", status:"done", sceneId:"lu_huan_w147" },
  { w:148, season:3, title:"Hugo te demande la vérité", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w148" },
  { w:149, season:3, title:"Tante Mei : prends ton temps", type:"chitchat", contact:"tante_mei", status:"done", sceneId:"tante_mei_w149_prompt" },
  { w:150, season:3, title:"Lin : on se voit demain ?", type:"chitchat", contact:"lin", status:"done", sceneId:"lin_w150_prompt", note:"Skinner" },
  { w:151, season:3, title:"Amanda : invitation pour parler ?", type:"empty", contact:"amanda", status:"done", sceneId:"amanda_w151" },
  { w:152, season:3, title:"Première vraie rencontre IRL avec Lin", type:"empty", contact:"lin", status:"done", sceneId:"lin_w152" },
  { w:153, season:3, title:"Maman : photo Tante Mei guérie", type:"chitchat", contact:"maman", status:"done", sceneId:"maman_w153_prompt" },
  { w:154, season:3, title:"Lu Huan : tu veux qu'on parle ?", type:"empty", contact:"lu_huan", status:"done", sceneId:"lu_huan_w154" },
  { w:155, season:3, title:"Inconnu : choisis ton camp", type:"chitchat", contact:"inconnu", status:"done", sceneId:"inconnu_w155_prompt" },
  { w:156, season:3, title:"Réveillon A3 avec Lin", type:"cinematic", contact:"maman", status:"done", sceneId:"reveillon_a3" },
  { w:157, season:4, title:"Bonne année 2030", type:"chitchat", contact:"maman", status:"done", sceneId:"maman_w157_prompt" },
  { w:158, season:4, title:"Wei : nouveau job ailleurs ?", type:"empty", contact:"wei", status:"done", sceneId:"wei_w158" },
  { w:159, season:4, title:"Tante Mei : je veux te léguer le village", type:"empty", contact:"tante_mei", status:"done", sceneId:"tante_mei_w159" },
  { w:160, season:4, title:"Rumeurs fusion Lu/Hatsune", type:"major", contact:"amanda", status:"done", sceneId:"rumeurs_fusion_lu" },
  { w:161, season:4, title:"Hugo : on doit reparler de nous", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w161" },
  { w:162, season:4, title:"Lin : voilà ce que j'ai trouvé", type:"empty", contact:"lin", status:"done", sceneId:"lin_w162" },
  { w:163, season:4, title:"Dernière manche, 60 jours pour décider", type:"major", contact:"lu_huan", status:"done", sceneId:"derniere_manche" },
  { w:164, season:4, title:"Maman : journaliste demande à parler", type:"empty", contact:"maman", status:"done", sceneId:"maman_w164" },
  { w:165, season:4, title:"Wei : témoin si besoin", type:"empty", contact:"wei", status:"done", sceneId:"wei_w165" },
  { w:166, season:4, title:"Liu Wei : sois prudente", type:"chitchat", contact:"liu_wei", status:"done", sceneId:"liu_wei_w166_prompt" },
  { w:167, season:4, title:"Amanda essaie de revenir dans le jeu", type:"empty", contact:"amanda", status:"done", sceneId:"amanda_w167" },
  { w:168, season:4, title:"Lu Huan : board veut votre tête", type:"chitchat", contact:"lu_huan", status:"done", sceneId:"lu_huan_w168_prompt", note:"Skinner" },
  { w:169, season:4, title:"Tante Mei : photos des élèves de l'école", type:"chitchat", contact:"tante_mei", status:"done", sceneId:"tante_mei_w169_prompt" },
  { w:170, season:4, title:"Hugo te quitte si mood < 4", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w170", note:"Conditionnel" },
  { w:171, season:4, title:"Lin : j'ai besoin de plus de temps", type:"empty", contact:"lin", status:"done", sceneId:"lin_w171" },
  { w:172, season:4, title:"Maman : tu rentres pour Pâques ?", type:"chitchat", contact:"maman", status:"done", sceneId:"maman_w172_prompt" },
  { w:173, season:4, title:"Confrontation finale — Lin propose 4 voies", type:"major", contact:"lin", status:"done", sceneId:"confrontation_finale" },
  { w:174, season:4, title:"Wei : pas la peine, je suis avec toi", type:"empty", contact:"wei", status:"done", sceneId:"wei_w174" },
  { w:175, season:4, title:"Lu Huan : un dernier dîner, peut-être ?", type:"empty", contact:"lu_huan", status:"done", sceneId:"lu_huan_w175" },
  { w:176, season:4, title:"Inconnu : ne te retourne pas", type:"chitchat", contact:"inconnu", status:"done", sceneId:"inconnu_w176_prompt" },
  { w:177, season:4, title:"Tante Mei : armoire bleue est à toi désormais", type:"empty", contact:"tante_mei", status:"done", sceneId:"tante_mei_w177" },
  { w:178, season:4, title:"Mariage de Liu Wei au village", type:"empty", contact:"liu_wei", status:"done", sceneId:"liu_wei_w178" },
  { w:179, season:4, title:"Hugo : silence", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w179" },
  { w:180, season:4, title:"Amanda : information bonus", type:"empty", contact:"amanda", status:"done", sceneId:"amanda_w180" },
  { w:181, season:4, title:"Lin : on a un témoin", type:"empty", contact:"lin", status:"done", sceneId:"lin_w181" },
  { w:182, season:4, title:"Maman propose de venir à NeoCity", type:"empty", contact:"maman", status:"done", sceneId:"maman_w182" },
  { w:183, season:4, title:"Wei : appelle un avocat", type:"chitchat", contact:"wei", status:"done", sceneId:"wei_w183_prompt" },
  { w:184, season:4, title:"Lu Huan : il faut qu'on parle face à face", type:"empty", contact:"lu_huan", status:"done", sceneId:"lu_huan_w184" },
  { w:185, season:4, title:"Tante Mei : ton père aurait été fier", type:"chitchat", contact:"tante_mei", status:"done", sceneId:"tante_mei_w185_prompt" },
  { w:186, season:4, title:"Inconnu masqué : arrête tout", type:"chitchat", contact:"inconnu", status:"done", sceneId:"inconnu_w186_prompt", note:"Skinner" },
  { w:187, season:4, title:"Hugo : photo d'archive entre nous", type:"chitchat", contact:"hugo", status:"done", sceneId:"hugo_w187_prompt" },
  { w:188, season:4, title:"Soir tendu chez Lu Huan", type:"empty", contact:"lu_huan", status:"done", sceneId:"lu_huan_w188" },
  { w:189, season:4, title:"Lin : prête à témoigner", type:"empty", contact:"lin", status:"done", sceneId:"lin_w189" },
  { w:190, season:4, title:"Monte la pression médias", type:"major", contact:"amanda", status:"done", sceneId:"monte_pression" },
  { w:191, season:4, title:"Wei : je serai là le jour J", type:"chitchat", contact:"wei", status:"done", sceneId:"wei_w191_prompt" },
  { w:192, season:4, title:"Tante Mei : je viens à NeoCity", type:"empty", contact:"tante_mei", status:"done", sceneId:"tante_mei_w192" },
  { w:193, season:4, title:"Maman : je suis dans l'avion", type:"empty", contact:"maman", status:"done", sceneId:"maman_w193" },
  { w:194, season:4, title:"Hugo : je serai là si tu veux", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w194" },
  { w:195, season:4, title:"Décision intime nuit pavillon Lu", type:"empty", contact:"lu_huan", status:"done", sceneId:"lu_huan_w195" },
  { w:196, season:4, title:"Lin : tu choisis quoi ?", type:"empty", contact:"lin", status:"done", sceneId:"lin_w196" },
  { w:197, season:4, title:"Maman : reviens, ma fille", type:"chitchat", contact:"maman", status:"done", sceneId:"maman_w197", note:"Skinner" },
  { w:198, season:4, title:"Avant-dernier acte", type:"major", contact:"lu_huan", status:"done", sceneId:"avant_dernier_acte" },
  { w:199, season:4, title:"Wei : tu es prête ?", type:"chitchat", contact:"wei", status:"done", sceneId:"wei_w199_prompt" },
  { w:200, season:4, title:"Inconnu : courage", type:"chitchat", contact:"inconnu", status:"done", sceneId:"inconnu_w200_prompt" },
  { w:201, season:4, title:"Lu Huan : quoi qu'il arrive", type:"chitchat", contact:"lu_huan", status:"done", sceneId:"lu_huan_w201_prompt" },
  { w:202, season:4, title:"Préparation finale (dossier, témoins)", type:"empty", contact:"shen", status:"done", sceneId:"prep_w202" },
  { w:203, season:4, title:"Tante Mei : prie pour toi", type:"chitchat", contact:"tante_mei", status:"done", sceneId:"tante_mei_w203_prompt" },
  { w:204, season:4, title:"Hugo : embrasse-moi avant", type:"empty", contact:"hugo", status:"done", sceneId:"hugo_w204" },
  { w:205, season:4, title:"Imminence finale", type:"major", contact:"maman", status:"done", sceneId:"imminence_finale" },
  { w:206, season:4, title:"Lin : à demain", type:"chitchat", contact:"lin", status:"done", sceneId:"lin_w206_prompt" },
  { w:207, season:4, title:"Maman : c'est ton heure", type:"empty", contact:"maman", status:"done", sceneId:"maman_w207" },
  { w:208, season:4, title:"Ending choisi → 1 des 4 fins", type:"cinematic", contact:"shen", status:"done", sceneId:"ending_choisi" }
];

// ----- Photos -----
// Statuts : 'produced' (déjà dans drama/ressources) | 'todo' (à shooter)
// kind : 'chat' (image dans conversation), 'post' (Instagram), 'wallpaper', 'map'
const PHOTOS = [
  { id:'chat_selfie_arrivee_shen', file:'chat_selfie_arrivee_shen.jpeg', kind:'chat', season:1, weeks:[1], characters:['shen'], desc:'Selfie aéroport — arrivée Shen', status:'produced' },
  { id:'post_shen_train', file:'post_shen_train.png', kind:'post', season:1, weeks:[1], characters:['shen'], desc:'Post Insta arrivée train', status:'produced' },
  { id:'post_shen_depart', file:'post_shen_depart.png', kind:'post', season:1, weeks:[1], characters:['shen'], desc:'Post départ village', status:'produced' },
  { id:'chat_taxi_recu', file:'chat_taxi_recu.png', kind:'chat', season:1, weeks:[1,2], characters:['shen'], desc:'Reçu taxi première arrivée', status:'produced' },
  { id:'chat_badge_visiteur', file:'chat_badge_visiteur.jpeg', kind:'chat', season:1, weeks:[2], characters:['shen','wei'], desc:'Badge visiteur premier jour', status:'produced' },
  { id:'chat_wei_screenshot_badge', file:'chat_wei_screenshot_badge.png', kind:'chat', season:1, weeks:[2,7], characters:['wei'], desc:'Screenshot badge envoyé par Wei', status:'produced' },
  { id:'post_shen_studio', file:'post_shen_studio.png', kind:'post', season:1, weeks:[3], characters:['shen'], desc:'Post studio (W3 — tour du studio)', status:'produced' },
  { id:'chat_recu_loyer', file:'chat_recu_loyer.png', kind:'chat', season:1, weeks:[3,4], characters:['shen'], desc:'Reçu loyer (économie S1)', status:'produced' },
  { id:'chat_billets', file:'chat_billets.jpg', kind:'chat', season:1, weeks:[10,27], characters:['shen','maman'], desc:'Photo billets (économie / Tante Mei malade)', status:'produced' },
  { id:'chat_maman_plat', file:'chat_maman_plat.png', kind:'chat', season:1, weeks:[4,17,42], characters:['maman'], desc:'Photo plat de Maman (chitchat récurrent)', status:'produced' },
  { id:'post_maman_plat', file:'post_maman_plat.png', kind:'post', season:1, weeks:[17], characters:['maman'], desc:'Post Insta — plat Maman', status:'produced' },
  { id:'chat_tour_groupe_lu', file:'chat_tour_groupe_lu.jpg', kind:'chat', season:1, weeks:[12], characters:['lu_huan'], desc:'Tour Groupe Lu vue extérieure', status:'produced' },
  { id:'chat_lu_office_view', file:'chat_lu_office_view.png', kind:'chat', season:1, weeks:[12,30], characters:['lu_huan'], desc:'Bureau Lu, vue de l\'open space', status:'produced' },
  { id:'post_wei_tour', file:'post_wei_tour.png', kind:'post', season:1, weeks:[12], characters:['wei'], desc:'Post Wei devant la tour Lu', status:'produced' },
  { id:'post_wei_cafe', file:'post_wei_cafe.png', kind:'post', season:1, weeks:[15,19], characters:['wei'], desc:'Post Wei au café (vie sociale)', status:'produced' },
  { id:'chat_amanda_selfie_cafet', file:'chat_amanda_selfie_cafet.png', kind:'chat', season:1, weeks:[14,26], characters:['amanda'], desc:'Selfie Amanda à la cafétéria', status:'produced' },
  { id:'post_amanda_cadeau', file:'post_amanda_cadeau.png', kind:'post', season:1, weeks:[14], characters:['amanda'], desc:'Post Amanda — cadeau pour soi', status:'produced' },
  { id:'chat_shen_ascenseur_selfie', file:'chat_shen_ascenseur_selfie.png', kind:'chat', season:1, weeks:[40], characters:['shen','amanda'], desc:'Photo ascenseur — Le piège (W40)', status:'produced' },
  { id:'post_amanda_robe', file:'post_amanda_robe.png', kind:'post', season:2, weeks:[82,90], characters:['amanda'], desc:'Robe gala — soirée Lu', status:'produced' },
  { id:'post_lu_archi', file:'post_lu_archi.png', kind:'post', season:2, weeks:[63], characters:['lu_huan'], desc:'Post archi — lancement produit', status:'produced' },
  { id:'post_lu_nuit', file:'post_lu_nuit.png', kind:'post', season:2, weeks:[90], characters:['lu_huan'], desc:'Post Lu de nuit (gala)', status:'produced' },
  { id:'post_lu_portrait', file:'post_lu_portrait.png', kind:'post', season:2, weeks:[63,73], characters:['lu_huan'], desc:'Portrait Lu Huan officiel', status:'produced' },
  { id:'map_neocity', file:'map_neocity.jpg', kind:'map', season:1, weeks:[1,2], characters:[], desc:'Carte de NeoCity (app Maps)', status:'produced' },
  { id:'wallpaper_home', file:'wallpaper_home.png', kind:'wallpaper', season:1, weeks:[], characters:[], desc:'Wallpaper home (UI)', status:'produced' },
  { id:'wallpaper_home_dark', file:'wallpaper_home_dark.png', kind:'wallpaper', season:1, weeks:[], characters:[], desc:'Wallpaper home dark (UI)', status:'produced' },
  { id:'wallpaper_lock', file:'wallpaper_lock.jpeg', kind:'wallpaper', season:1, weeks:[], characters:[], desc:'Wallpaper lock screen (sakura)', status:'produced' },
  { id:'wallpaper_lock_dark', file:'wallpaper_lock_dark.png', kind:'wallpaper', season:1, weeks:[], characters:[], desc:'Wallpaper lock screen dark', status:'produced' },
  { id:'todo_w8_vieille_photo_papa', file:null, kind:'chat', season:1, weeks:[8], characters:['tante_mei','papa'], desc:'Vieille photo papa envoyée par Tante Mei (W8)', status:'todo' },
  { id:'todo_w22_hugo_hanami', file:null, kind:'chat', season:1, weeks:[22], characters:['hugo'], desc:'Café Hanami — rencontre Hugo', status:'todo' },
  { id:'todo_w23_hugo_croquis', file:null, kind:'chat', season:1, weeks:[23], characters:['hugo'], desc:'Croquis envoyé par Hugo', status:'todo' },
  { id:'todo_w24_chat_voisine', file:null, kind:'chat', season:1, weeks:[24], characters:['maman'], desc:'Chat de la voisine (Maman)', status:'todo' },
  { id:'todo_w33_hugo_peinture', file:null, kind:'chat', season:1, weeks:[33], characters:['hugo'], desc:'Peinture de Shen par Hugo', status:'todo' },
  { id:'todo_w35_armoire_bleue', file:null, kind:'chat', season:1, weeks:[35,120], characters:['inconnu','tante_mei'], desc:'Photo armoire bleue (mystère)', status:'todo' },
  { id:'todo_w37_couple_hugo', file:null, kind:'post', season:1, weeks:[37], characters:['shen','hugo'], desc:'Post couple Shen + Hugo', status:'todo' },
  { id:'todo_w39_colis_tante_mei', file:null, kind:'chat', season:1, weeks:[39,87], characters:['tante_mei'], desc:'Colis envoyé par Tante Mei', status:'todo' },
  { id:'todo_w47_liu_wei_arrive', file:null, kind:'chat', season:1, weeks:[47,48], characters:['liu_wei'], desc:'Liu Wei arrive du village + photos village', status:'todo' },
  { id:'todo_w50_grand_oeuvre', file:null, kind:'chat', season:1, weeks:[50], characters:['lu_huan','shen'], desc:'Salle comité — grand œuvre', status:'todo' },
  { id:'todo_w52_reveillon_a1', file:null, kind:'post', season:1, weeks:[52], characters:['maman','shen'], desc:'Réveillon A1 — table famille', status:'todo' },
  { id:'todo_w55_photo_papa_jeune', file:null, kind:'chat', season:2, weeks:[55,89], characters:['tante_mei','papa'], desc:'Photo papa jeune retrouvée', status:'todo' },
  { id:'todo_w57_galerie_hugo', file:null, kind:'post', season:2, weeks:[57], characters:['hugo'], desc:'Galerie Hugo — exposition', status:'todo' },
  { id:'todo_w63_lancement_produit', file:null, kind:'chat', season:2, weeks:[63,64], characters:['lu_huan'], desc:'Scène lancement produit (média)', status:'todo' },
  { id:'todo_w70_carnet_papa', file:null, kind:'chat', season:2, weeks:[70,78,133], characters:['shen','papa'], desc:'Carnet de notes du papa', status:'todo' },
  { id:'todo_w77_florence', file:null, kind:'post', season:2, weeks:[77,88], characters:['hugo','shen'], desc:'Florence — voyage Hugo', status:'todo' },
  { id:'todo_w83_bourse_tip', file:null, kind:'chat', season:2, weeks:[83], characters:['lu_huan'], desc:'Capture tuyau bourse (graphe)', status:'todo' },
  { id:'todo_w89_lin_enfant', file:null, kind:'chat', season:2, weeks:[89], characters:['maman','lin'], desc:'Photo Lin enfant', status:'todo' },
  { id:'todo_w90_gala_robe', file:null, kind:'post', season:2, weeks:[90], characters:['shen'], desc:'Shen au gala (robe pro)', status:'todo' },
  { id:'todo_w104_reveillon_a2', file:null, kind:'post', season:2, weeks:[104], characters:['maman','shen'], desc:'Réveillon A2', status:'todo' },
  { id:'todo_w118_mahjong', file:null, kind:'chat', season:3, weeks:[118], characters:['maman','tante_mei'], desc:'Mahjong au village', status:'todo' },
  { id:'todo_w123_registre_lu', file:null, kind:'chat', season:3, weeks:[123], characters:['inconnu'], desc:'Copie registre Lu Senior — passé révélé', status:'todo' },
  { id:'todo_w128_tante_mei_revele', file:null, kind:'chat', season:3, weeks:[128], characters:['tante_mei','papa'], desc:'Photo papa au Groupe Lu (révélation)', status:'todo' },
  { id:'todo_w144_dossier_hatsune', file:null, kind:'chat', season:3, weeks:[144], characters:['lu_huan'], desc:'Dossier Hatsune découvert pavillon Lu', status:'todo' },
  { id:'todo_w145_lin_irl', file:null, kind:'chat', season:3, weeks:[145,152], characters:['lin'], desc:'Lin révélée — première vraie photo', status:'todo' },
  { id:'todo_w153_tante_mei_guerie', file:null, kind:'chat', season:3, weeks:[153], characters:['tante_mei'], desc:'Tante Mei guérie (Maman envoie)', status:'todo' },
  { id:'todo_w156_reveillon_a3', file:null, kind:'post', season:3, weeks:[156], characters:['maman','lin','shen'], desc:'Réveillon A3 avec Lin', status:'todo' },
  { id:'todo_w160_fusion_lu_hatsune', file:null, kind:'post', season:4, weeks:[160], characters:['amanda','lu_huan'], desc:'Article fusion Lu/Hatsune (Insta media)', status:'todo' },
  { id:'todo_w169_eleves_ecole', file:null, kind:'chat', season:4, weeks:[169], characters:['tante_mei'], desc:'Photos élèves de l\'école au village', status:'todo' },
  { id:'todo_w173_confrontation', file:null, kind:'chat', season:4, weeks:[173], characters:['lin'], desc:'Confrontation finale — 4 voies', status:'todo' },
  { id:'todo_w177_armoire_bleue_legs', file:null, kind:'chat', season:4, weeks:[177], characters:['tante_mei'], desc:'Armoire bleue léguée à Shen', status:'todo' },
  { id:'todo_w178_mariage_liu_wei', file:null, kind:'post', season:4, weeks:[178], characters:['liu_wei'], desc:'Mariage Liu Wei au village', status:'todo' },
  { id:'todo_w187_archive_hugo', file:null, kind:'chat', season:4, weeks:[187], characters:['hugo','shen'], desc:'Photo d\'archive Hugo + Shen', status:'todo' },
  { id:'todo_w190_pression_medias', file:null, kind:'post', season:4, weeks:[190], characters:['amanda'], desc:'Capture article presse (pression)', status:'todo' },
  { id:'todo_w198_avant_dernier', file:null, kind:'chat', season:4, weeks:[198], characters:['lu_huan'], desc:'Avant-dernier acte — décor pavillon', status:'todo' },
  { id:'todo_w205_imminence', file:null, kind:'chat', season:4, weeks:[205], characters:['maman'], desc:'Imminence finale — message Maman', status:'todo' },
  { id:'todo_ending_justice', file:null, kind:'post', season:4, weeks:[208], characters:['shen'], desc:'⚖️ Ending Justice — procès médiatique', status:'todo' },
  { id:'todo_ending_argent', file:null, kind:'post', season:4, weeks:[208], characters:['shen'], desc:'💴 Ending Argent — fortune offshore', status:'todo' },
  { id:'todo_ending_vengeance', file:null, kind:'post', season:4, weeks:[208], characters:['shen'], desc:'🗡 Ending Vengeance — Groupe Lu démoli', status:'todo' },
  { id:'todo_ending_paix', file:null, kind:'post', season:4, weeks:[208], characters:['shen'], desc:'🌸 Ending Paix — école au village', status:'todo' }
];

// ----- Batches d'écriture (priorité Saison 1) -----
const BATCHES = [
  { id:'B1', season:1, weeks:[3,5,6,8,9,10,11], theme:'Installation, premières habitudes, Maman/Wei' },
  { id:'B2', season:1, weeks:[13,15,17,19,20,21], theme:'Premier mois bureau, Amanda creuse, Maman tendre' },
  { id:'B3', season:1, weeks:[23,24,25,26,28,29], theme:'Hugo prend de la place, Lu Huan évalue' },
  { id:'B4', season:1, weeks:[31,32,33,36,37,38,39], theme:'Pression pro, ambiguïté Hugo, mystère armoire bleue' },
  { id:'B5', season:1, weeks:[41,42,43,44,45,46], theme:'Crise Amanda + Hugo en doute' },
  { id:'B6', season:1, weeks:[48,49,51], theme:'Liu Wei arrive, premier triangle, pre-Réveillon' }
];

// ----- Arcs narratifs (1 sem = 1 scène autonome, arcs émergent par juxtaposition) -----
const ARCS = [
  { id:'A_install', season:1, weeks:[1,2,3,4,5,6,7,8,9,10,11], titre:"Installation & famille", theme:"Shen débarque, Wei guide, premiers signaux faibles (L. plante, photo papa, money pressure, Liu Wei évoqué)" },
  { id:'B_lu_intro', season:1, weeks:[12,13,14,15,16,17,18,19,20,21], titre:"Lu Europe — premier contact", theme:"Lu Huan teste, Amanda jauge, Wei prévient, NDA, première crise santé Tante Mei" },
  { id:'C_hugo_lu', season:1, weeks:[22,23,24,25,26,27,28,29,30], titre:"Hugo arrive, Lu observe", theme:"Romance ambigüe, Amanda joue la fausse compassion, money crisis 600€, signature douteuse Lu Huan" },
  { id:'D_filet', season:1, weeks:[31,32,33,34,35,36,37,38,39,40,41,42], titre:"Le filet se resserre", theme:"Climax humiliation Amanda (W40), premier vrai mystère papa (armoire bleue), Hugo possessif, Lu enregistre" },
  { id:'E_reconstr', season:1, weeks:[43,44,45,46,47,48,49,50,51,52], titre:"Défaite & reconstruction", theme:"Liu Wei arrive, doute Hugo, projet Hatsune planté, Réveillon A1 avec cliffhanger SMS anonyme" }
];

// ----- Quick-status (objectif vs réalisé, à mettre à jour à chaque commit majeur) -----
const QUICK_STATUS = {
  scenes_total_target: 208,
  scenes_done: 208,
  pct: 100,
  achievements: { target: 10, current: 10 },
  apps: { target: 11, current: 11 }
};

if (typeof module !== 'undefined') module.exports = { LORE, PERSONNAGES, TIMELINE, PHOTOS, BATCHES, ARCS, QUICK_STATUS, RAW_BASE };
