// Drama — données du dashboard
// Source de vérité : ROADMAP.md du repo teiki5320/drama
// Toute modification ici doit refléter une mise à jour du ROADMAP.

const RAW_BASE = 'https://raw.githubusercontent.com/teiki5320/drama/main/Drama.swiftpm/Sources/AppModule/ressources/';

const LORE = {
  pitch: "Drama — jeu narratif iPhone/iPad. Le joueur incarne Shen Miao, jeune femme asiatique de 24 ans qui s'installe en Europe en 2026 pour son master + stage chez Lu Europe, et qui découvrira que la famille Lu a fait tuer son père en 2007.",
  format: { semaines: 208, ans: 4, scenesParSemaine: 1 },
  saisons: [
    { id: 1, label: 'Saison 1 — Arrivée et installation', range: 'W1-52', model: 'Gratuite' },
    { id: 2, label: 'Saison 2 — Fin du master + ascension', range: 'W53-104', model: 'Payante' },
    { id: 3, label: 'Saison 3 — Vie pro + révélations', range: 'W105-156', model: 'Payante' },
    { id: 4, label: 'Saison 4 — Endgame', range: 'W157-208', model: 'Payante' }
  ],
  faitsFiges: [
    { annee: 2002, fait: 'Naissance de Shen Miao au village' },
    { annee: 2007, fait: 'Shen Liwei (papa, 38 ans, comptable Groupe Lu) refuse une promotion → tué dans un faux accident de moto' },
    { annee: 2014, fait: 'Lu Senior (grand-père, fondateur, intercepteur de la lettre du papa) meurt de vieillesse. Lu Mingzhe (fils) prend le pouvoir.' },
    { annee: 2014, fait: 'Lu Huan (14 ans) apprend que son père « a fait quelque chose »' },
    { annee: 2018, fait: 'Lu Mingzhe (vrai commanditaire) meurt d\'AVC' },
    { annee: 2020, fait: 'Lin (cousine, 22 ans) disparaît après être partie en Europe' },
    { annee: 2026, fait: 'Shen 24 ans → arrive en Europe (W1)' },
    { annee: 2030, fait: 'Shen 28 ans → fin du jeu (W208)' }
  ],
  troisLu: [
    { id: 'lu_senior', nom: 'Lu Senior', role: 'Grand-père, fondateur', etat: 'Mort de vieillesse en 2014', ingame: 'Hors d\'atteinte. Intercepteur de la lettre du papa.', warn: 'NE PAS confondre avec Lu Mingzhe.' },
    { id: 'lu_mingzhe', nom: 'Lu Mingzhe', role: 'Fils de Senior', etat: 'Mort d\'AVC en 2018', ingame: 'HORS JEU. Mais c\'est LE VRAI commanditaire du meurtre.', warn: 'NE JAMAIS le faire apparaître. Il est mort.' },
    { id: 'lu_huan', nom: 'Lu Huan', role: 'PDG actuel, héritier', etat: 'Vivant — antagoniste principal en jeu', ingame: 'Présent. PAS l\'auteur du crime, mais il sait ou soupçonne.', warn: 'C\'est lui qu\'on rencontre, pas son père.' }
  ],
  endings: [
    { id: 'ending_justice', label: 'Justice', emoji: '⚖️', desc: 'Procès médiatique', ecrit: true },
    { id: 'ending_argent', label: 'Argent', emoji: '💴', desc: 'Fortune offshore', ecrit: true },
    { id: 'ending_vengeance', label: 'Vengeance', emoji: '🗡', desc: 'Groupe Lu démoli', ecrit: true },
    { id: 'ending_paix', label: 'Paix', emoji: '🌸', desc: 'École au village', ecrit: true }
  ]
};

const PERSONNAGES = [
  { id: 'shen', nom: 'Shen Miao', role: 'Protagoniste', faction: 'protagoniste', firstW: 1, lastW: 208, saisons: [1,2,3,4], desc: '24 ans en 2026, Asiatique, master + stage Lu Europe.', actif: true },
  { id: 'maman', nom: 'Maman', role: 'Mère de Shen', faction: 'famille', firstW: 1, lastW: 208, saisons: [1,2,3,4], desc: 'Au village. Voix off chaude, chitchats récurrents.', actif: true },
  { id: 'wei', nom: 'Wei', role: 'Cousin·e ami·e à NeoCity', faction: 'famille', firstW: 2, lastW: 208, saisons: [1,2,3,4], desc: 'Premier soutien IRL. Pivot du tournant S3 (W138 « Wei savait »).', actif: true },
  { id: 'tante_mei', nom: 'Tante Mei', role: 'Tante au village', faction: 'famille', firstW: 8, lastW: 208, saisons: [1,2,3,4], desc: 'Garde la mémoire du papa. Carnet, armoire bleue, révélations S3.', actif: true },
  { id: 'lu_huan', nom: 'Lu Huan', role: 'PDG Groupe Lu', faction: 'lu', firstW: 12, lastW: 208, saisons: [1,2,3,4], desc: 'Héritier. Antagoniste ambigu, devient humain à W142.', actif: true },
  { id: 'amanda', nom: 'Amanda', role: 'Collègue toxique', faction: 'lu', firstW: 12, lastW: 208, saisons: [1,2,3,4], desc: 'Pique au bureau, piège ascenseur W40, trahison W93.', actif: true },
  { id: 'hugo', nom: 'Hugo', role: 'Artiste, romance', faction: 'romance', firstW: 22, lastW: 208, saisons: [1,2,3,4], desc: 'Rencontré au café Hanami. Triangle vs Liu Wei à partir de S1 fin.', actif: true },
  { id: 'liu_wei', nom: 'Liu Wei', role: 'Du village, romance alternative', faction: 'romance', firstW: 47, lastW: 208, saisons: [1,2,3,4], desc: 'Arrive à NeoCity. Triangle avec Hugo.', actif: true },
  { id: 'lin', nom: 'Lin', role: 'Cousine disparue', faction: 'famille', firstW: 117, lastW: 208, saisons: [3,4], desc: 'Disparue 2020. Premiers messages codés W117. Révélée W145.', actif: true },
  { id: 'inconnu', nom: 'Inconnu / L.', role: 'Numéro mystère', faction: 'mystere', firstW: 5, lastW: 208, saisons: [1,2,3,4], desc: 'Skinner, pings énigmatiques. Identité révélée tard.', actif: true },
  { id: 'rh', nom: 'RH (inconnu)', role: 'Ressources humaines Lu', faction: 'lu', firstW: 13, lastW: 104, saisons: [1,2], desc: 'Mails formels, étape pression carrière.', actif: true },
  { id: 'papa', nom: 'Shen Liwei (papa)', role: 'Père de Shen, mort en 2007', faction: 'reference', firstW: null, lastW: null, saisons: [], desc: 'Hors-écran. Évoqué via carnet (W133), photos (W8, W55), souvenirs.', actif: false },
  { id: 'lu_senior', nom: 'Lu Senior', role: 'Grand-père, fondateur (†2014)', faction: 'reference', firstW: null, lastW: null, saisons: [], desc: 'Référence lore uniquement. Ne pas confondre avec Mingzhe.', actif: false },
  { id: 'lu_mingzhe', nom: 'Lu Mingzhe', role: 'Vrai commanditaire (†2018)', faction: 'reference', firstW: null, lastW: null, saisons: [], desc: 'Référence lore uniquement. HORS JEU mais c\'est LUI le coupable.', actif: false }
];

const TIMELINE = [
  { w:1, season:1, title:'Arrivée NeoCity, message Maman + selfie aéroport', type:'major', contact:'maman', status:'done', sceneId:'start' },
  { w:2, season:1, title:'Premier jour campus + stage, intro Wei', type:'major', contact:'wei', status:'done', sceneId:'wei_morning' },
  { w:3, season:1, title:'Fais le tour du studio', type:'chitchat', contact:'wei', status:'todo', batch:'B1' },
  { w:4, season:1, title:'Maman appelle « comment ça va »', type:'chitchat', contact:'maman', status:'done', sceneId:'chitchat_maman_w4' },
  { w:5, season:1, title:'Premier numéro inconnu', type:'chitchat', contact:'inconnu', status:'todo', note:'Skinner ping existe', batch:'B1' },
  { w:6, season:1, title:'Wei te montre la cantine', type:'chitchat', contact:'wei', status:'todo', batch:'B1' },
  { w:7, season:1, title:'Wei : exam jeudi', type:'chitchat', contact:'wei', status:'done', sceneId:'chitchat_wei_w7' },
  { w:8, season:1, title:'Tante Mei envoie une vieille photo', type:'empty', contact:'tante_mei', status:'todo', batch:'B1' },
  { w:9, season:1, title:'Amanda envoie un sticker', type:'chitchat', contact:'amanda', status:'todo', note:'Skinner', batch:'B1' },
  { w:10, season:1, title:'Maman : ne dépense pas trop', type:'chitchat', contact:'maman', status:'todo', batch:'B1' },
  { w:11, season:1, title:'Wei te présente Liu Wei (au téléphone)', type:'chitchat', contact:'wei', status:'todo', batch:'B1' },
  { w:12, season:1, title:'Première semaine bureau, intro Lu Huan + Amanda', type:'major', contact:'lu_huan', status:'done', sceneId:'bureau_premiere_semaine' },
  { w:13, season:1, title:'Premier mail RH', type:'chitchat', contact:'rh', status:'todo', batch:'B2' },
  { w:14, season:1, title:'Amanda pique pull du village', type:'major', contact:'amanda', status:'done', sceneId:'amanda_petite_pique' },
  { w:15, season:1, title:'Wei te console après Amanda', type:'chitchat', contact:'wei', status:'todo', batch:'B2' },
  { w:16, season:1, title:'Lu Huan demande heures sup', type:'major', contact:'lu_huan', status:'done', sceneId:'lu_huan_demande_overtime' },
  { w:17, season:1, title:'Maman : ton père aurait été fier', type:'chitchat', contact:'maman', status:'todo', batch:'B2' },
  { w:18, season:1, title:'Tante Mei appelle (santé Maman)', type:'major', contact:'tante_mei', status:'done', sceneId:'tante_mei_appelle' },
  { w:19, season:1, title:'Wei pleure pour son ex', type:'chitchat', contact:'wei', status:'todo', batch:'B2' },
  { w:20, season:1, title:'Insta : Hugo like un de tes posts (Skinner)', type:'chitchat', contact:'inconnu', status:'todo', batch:'B2' },
  { w:21, season:1, title:'Lu Huan : compliment public', type:'chitchat', contact:'lu_huan', status:'todo', batch:'B2' },
  { w:22, season:1, title:'Rencontre Hugo café Hanami', type:'major', contact:'hugo', status:'done', sceneId:'hugo_apparait' },
  { w:23, season:1, title:'Hugo t\'envoie un croquis', type:'chitchat', contact:'hugo', status:'todo', batch:'B3' },
  { w:24, season:1, title:'Maman : photo du chat de la voisine', type:'chitchat', contact:'maman', status:'todo', batch:'B3' },
  { w:25, season:1, title:'Premier vrai rendez-vous Hugo', type:'empty', contact:'hugo', status:'todo', batch:'B3' },
  { w:26, season:1, title:'Amanda : « tu vas aux RH ? » (faux concerne)', type:'chitchat', contact:'amanda', status:'todo', batch:'B3' },
  { w:27, season:1, title:'Tante Mei malade — 600€', type:'major', contact:'maman', status:'done', sceneId:'tante_mei_malade' },
  { w:28, season:1, title:'Wei te prête de l\'argent (ou pas)', type:'empty', contact:'wei', status:'todo', batch:'B3' },
  { w:29, season:1, title:'Lu Huan : tu veux le siège ?', type:'chitchat', contact:'lu_huan', status:'todo', batch:'B3' },
  { w:30, season:1, title:'Carrefour pro — Lu demande signature douteuse', type:'major', contact:'lu_huan', status:'done', sceneId:'carrefour_pro' },
  { w:31, season:1, title:'Inconnu : « tu as bien fait » ou « tu paieras »', type:'chitchat', contact:'inconnu', status:'todo', batch:'B4' },
  { w:32, season:1, title:'Maman : nouveaux voisins au village', type:'chitchat', contact:'maman', status:'todo', batch:'B4' },
  { w:33, season:1, title:'Hugo te peint sans te le dire', type:'empty', contact:'hugo', status:'todo', batch:'B4' },
  { w:34, season:1, title:'Hugo : tu fais quoi ce week-end', type:'chitchat', contact:'hugo', status:'done', sceneId:'chitchat_hugo_w34' },
  { w:35, season:1, title:'L. (numéro inconnu) — armoire bleue', type:'chitchat', contact:'inconnu', status:'todo', note:'Skinner existe' },
  { w:36, season:1, title:'Wei : promo en interne ?', type:'chitchat', contact:'wei', status:'todo', batch:'B4' },
  { w:37, season:1, title:'Tu postes une photo couple Hugo', type:'empty', contact:'hugo', status:'todo', batch:'B4' },
  { w:38, season:1, title:'Lu Huan croise Hugo dans un café', type:'empty', contact:'lu_huan', status:'todo', batch:'B4' },
  { w:39, season:1, title:'Tante Mei : envoie un colis', type:'chitchat', contact:'tante_mei', status:'todo', batch:'B4' },
  { w:40, season:1, title:'Le piège — Amanda diffuse photo ascenseur', type:'major', contact:'amanda', status:'done', sceneId:'le_piege' },
  { w:41, season:1, title:'Wei te défend en réunion', type:'empty', contact:'wei', status:'todo', batch:'B5' },
  { w:42, season:1, title:'Maman : tout va bien ma fille ?', type:'chitchat', contact:'maman', status:'todo', batch:'B5' },
  { w:43, season:1, title:'Amanda : fausse trêve', type:'empty', contact:'amanda', status:'todo', batch:'B5' },
  { w:44, season:1, title:'Hugo : doute amoureux', type:'empty', contact:'hugo', status:'todo', batch:'B5' },
  { w:45, season:1, title:'Lu Huan : projet Hatsune', type:'empty', contact:'lu_huan', status:'todo', batch:'B5' },
  { w:46, season:1, title:'Inconnu : ne signe rien', type:'chitchat', contact:'inconnu', status:'todo', batch:'B5' },
  { w:47, season:1, title:'Liu Wei arrive du village', type:'major', contact:'liu_wei', status:'done', sceneId:'liu_wei_arrive' },
  { w:48, season:1, title:'Liu Wei te montre des photos du village', type:'chitchat', contact:'liu_wei', status:'todo', batch:'B6' },
  { w:49, season:1, title:'Première hésitation Liu Wei vs Hugo', type:'empty', contact:'shen', status:'todo', batch:'B6' },
  { w:50, season:1, title:'Présentation grand œuvre devant comité', type:'major', contact:'lu_huan', status:'done', sceneId:'grand_oeuvre' },
  { w:51, season:1, title:'Maman : qu\'est-ce que tu deviens vraiment ?', type:'empty', contact:'maman', status:'todo', batch:'B6' },
  { w:52, season:1, title:'Réveillon A1', type:'cinematic', contact:'maman', status:'done', sceneId:'reveillon_a1' },
  { w:53, season:2, title:'Bonne année — Maman te rappelle', type:'chitchat', contact:'maman', status:'todo' },
  { w:54, season:2, title:'Wei : tu rentres au village pour les vacances ?', type:'chitchat', contact:'wei', status:'todo' },
  { w:55, season:2, title:'Tante Mei retrouve une photo du papa', type:'empty', contact:'tante_mei', status:'todo' },
  { w:56, season:2, title:'Lu Huan : promotion à venir', type:'empty', contact:'lu_huan', status:'todo' },
  { w:57, season:2, title:'Hugo expose en galerie', type:'empty', contact:'hugo', status:'todo' },
  { w:58, season:2, title:'Amanda : nouvelle collègue (toi en danger)', type:'chitchat', contact:'amanda', status:'todo' },
  { w:59, season:2, title:'Inconnu : prépare-toi', type:'chitchat', contact:'inconnu', status:'todo' },
  { w:60, season:2, title:'Liu Wei demande aide carte de séjour', type:'chitchat', contact:'liu_wei', status:'todo' },
  { w:61, season:2, title:'Wei : couple en crise (rupture imminente)', type:'empty', contact:'wei', status:'todo' },
  { w:62, season:2, title:'Maman tousse au téléphone', type:'empty', contact:'maman', status:'todo' },
  { w:63, season:2, title:'Lancement produit — présentation publique', type:'major', contact:'lu_huan', status:'done', sceneId:'lancement_produit' },
  { w:64, season:2, title:'Lendemain — médias en parlent', type:'empty', contact:'shen', status:'todo' },
  { w:65, season:2, title:'Hugo te dit qu\'il t\'aime', type:'empty', contact:'hugo', status:'todo' },
  { w:66, season:2, title:'Wei craque sous pression parents', type:'empty', contact:'wei', status:'todo' },
  { w:67, season:2, title:'Tante Mei : viens me voir cet été', type:'empty', contact:'tante_mei', status:'todo' },
  { w:68, season:2, title:'Lu Huan : voyage Singapour — tu viens ?', type:'empty', contact:'lu_huan', status:'todo' },
  { w:69, season:2, title:'Liu Wei : on devrait parler', type:'empty', contact:'liu_wei', status:'todo' },
  { w:70, season:2, title:'Tu trouves un carnet de notes du papa', type:'empty', contact:'shen', status:'todo' },
  { w:71, season:2, title:'Maman : rumeurs au village', type:'chitchat', contact:'maman', status:'todo' },
  { w:72, season:2, title:'Amanda : champagne à la fin du trimestre', type:'empty', contact:'amanda', status:'todo' },
  { w:73, season:2, title:'Crise Lu Huan — board veut le débarquer', type:'major', contact:'lu_huan', status:'done', sceneId:'crise_lu_huan' },
  { w:74, season:2, title:'Wei panique à propos du job', type:'empty', contact:'wei', status:'todo' },
  { w:75, season:2, title:'Hugo doute : tu as changé', type:'empty', contact:'hugo', status:'todo' },
  { w:76, season:2, title:'Inconnu : 14 mars 2007', type:'chitchat', contact:'inconnu', status:'todo' },
  { w:77, season:2, title:'Hugo t\'invite à Florence', type:'empty', contact:'hugo', status:'todo' },
  { w:78, season:2, title:'Tante Mei envoie carnet papa par poste', type:'empty', contact:'tante_mei', status:'todo' },
  { w:79, season:2, title:'Maman : reviens un week-end', type:'chitchat', contact:'maman', status:'todo' },
  { w:80, season:2, title:'Lu Huan te confie une tâche secrète', type:'empty', contact:'lu_huan', status:'todo' },
  { w:81, season:2, title:'Liu Wei : retour au village pour grand-mère', type:'empty', contact:'liu_wei', status:'todo' },
  { w:82, season:2, title:'Amanda : invitation soirée gala', type:'empty', contact:'amanda', status:'todo' },
  { w:83, season:2, title:'Tuyau bourse Lu Huan', type:'major', contact:'lu_huan', status:'done', sceneId:'opportunite_invest' },
  { w:84, season:2, title:'L. : c\'est un délit d\'initié', type:'chitchat', contact:'inconnu', status:'todo' },
  { w:85, season:2, title:'Wei : bilan trim, rénovation projet', type:'chitchat', contact:'wei', status:'todo' },
  { w:86, season:2, title:'Premier mois sans découvert', type:'chitchat', contact:'shen', status:'todo' },
  { w:87, season:2, title:'Tante Mei : photo arrivée colis', type:'chitchat', contact:'tante_mei', status:'todo' },
  { w:88, season:2, title:'Hugo : tu es prête pour Florence ?', type:'empty', contact:'hugo', status:'todo' },
  { w:89, season:2, title:'Maman : nouvelle photo de Lin enfant', type:'empty', contact:'maman', status:'todo' },
  { w:90, season:2, title:'Soirée gala Lu, première fois en robe pro', type:'empty', contact:'shen', status:'todo' },
  { w:91, season:2, title:'Amanda : compliment piégé', type:'chitchat', contact:'amanda', status:'todo' },
  { w:92, season:2, title:'Lu Huan : vous ressemblez à quelqu\'un', type:'empty', contact:'lu_huan', status:'todo' },
  { w:93, season:2, title:'Trahison Amanda — RH étudient anomalies', type:'major', contact:'amanda', status:'done', sceneId:'trahison_a2' },
  { w:94, season:2, title:'Wei te défend devant les RH', type:'empty', contact:'wei', status:'todo' },
  { w:95, season:2, title:'Hugo : les choses se compliquent ?', type:'empty', contact:'hugo', status:'todo' },
  { w:96, season:2, title:'Tante Mei : santé qui décline', type:'empty', contact:'tante_mei', status:'todo' },
  { w:97, season:2, title:'Liu Wei : on rentre tous les deux ?', type:'empty', contact:'liu_wei', status:'todo' },
  { w:98, season:2, title:'Maman : prends soin de toi', type:'chitchat', contact:'maman', status:'todo' },
  { w:99, season:2, title:'Lu Huan : restez après la réunion', type:'chitchat', contact:'lu_huan', status:'todo', note:'Skinner' },
  { w:100, season:2, title:'Soutenance master', type:'empty', contact:'shen', status:'todo' },
  { w:101, season:2, title:'Wei : on fête ça', type:'empty', contact:'wei', status:'todo' },
  { w:102, season:2, title:'Inconnu : ce n\'est qu\'un début', type:'chitchat', contact:'inconnu', status:'todo' },
  { w:103, season:2, title:'Climax A2 — choix carrière 3 voies', type:'major', contact:'lu_huan', status:'done', sceneId:'climax_a2' },
  { w:104, season:2, title:'Réveillon A2', type:'cinematic', contact:'maman', status:'done', sceneId:'reveillon_a2' },
  { w:105, season:3, title:'Premier mois en CDD/poste pro', type:'empty', contact:'lu_huan', status:'todo' },
  { w:106, season:3, title:'Hugo : il fait froid sans toi', type:'empty', contact:'hugo', status:'todo' },
  { w:107, season:3, title:'Wei te demande tuyau pro', type:'chitchat', contact:'wei', status:'todo' },
  { w:108, season:3, title:'Tante Mei : carnet est dans le coffre du salon', type:'empty', contact:'tante_mei', status:'todo' },
  { w:109, season:3, title:'Amanda : retour discret', type:'chitchat', contact:'amanda', status:'todo' },
  { w:110, season:3, title:'Hugo dit qu\'il t\'aime (à toi de répondre)', type:'empty', contact:'hugo', status:'todo' },
  { w:111, season:3, title:'Maman : ton père aurait dit quoi ?', type:'empty', contact:'maman', status:'todo' },
  { w:112, season:3, title:'Lu Huan : on parle bonus', type:'empty', contact:'lu_huan', status:'todo' },
  { w:113, season:3, title:'Promotion + clause de loyauté', type:'major', contact:'lu_huan', status:'done', sceneId:'promotion_a3' },
  { w:114, season:3, title:'Wei : promo aussi de son côté', type:'chitchat', contact:'wei', status:'todo' },
  { w:115, season:3, title:'Hugo : on prend un appart ?', type:'empty', contact:'hugo', status:'todo' },
  { w:116, season:3, title:'Liu Wei : nouvelles du village', type:'chitchat', contact:'liu_wei', status:'todo' },
  { w:117, season:3, title:'Lin envoie premier message codé', type:'empty', contact:'inconnu', status:'todo' },
  { w:118, season:3, title:'Maman : photo Mahjong Tante Mei', type:'chitchat', contact:'maman', status:'todo' },
  { w:119, season:3, title:'Amanda : tente une réconciliation utile', type:'empty', contact:'amanda', status:'todo' },
  { w:120, season:3, title:'Tante Mei envoie photo armoire bleue', type:'empty', contact:'tante_mei', status:'todo' },
  { w:121, season:3, title:'Lu Huan : suis-moi à un dîner privé', type:'empty', contact:'lu_huan', status:'todo' },
  { w:122, season:3, title:'Hugo : il faut qu\'on parle', type:'empty', contact:'hugo', status:'todo' },
  { w:123, season:3, title:'Passé révélé — copie registre Lu Senior', type:'major', contact:'inconnu', status:'done', sceneId:'passe_revele' },
  { w:124, season:3, title:'Wei : « je peux t\'aider »', type:'empty', contact:'wei', status:'todo' },
  { w:125, season:3, title:'Maman : tu m\'inquiètes ma fille', type:'chitchat', contact:'maman', status:'todo' },
  { w:126, season:3, title:'Wei propose de t\'aider à fouiller', type:'empty', contact:'wei', status:'todo' },
  { w:127, season:3, title:'Lu Huan : pourquoi cette froideur ?', type:'empty', contact:'lu_huan', status:'todo' },
  { w:128, season:3, title:'Tante Mei révèle papa lié au Groupe Lu', type:'major', contact:'tante_mei', status:'done', sceneId:'tante_mei_revele_papa' },
  { w:129, season:3, title:'Inconnu : courage', type:'chitchat', contact:'inconnu', status:'todo' },
  { w:130, season:3, title:'Liu Wei retourne au village (deuil)', type:'empty', contact:'liu_wei', status:'todo' },
  { w:131, season:3, title:'Hugo : tu deviens distante', type:'empty', contact:'hugo', status:'todo' },
  { w:132, season:3, title:'Maman : viens me voir au village', type:'empty', contact:'maman', status:'todo' },
  { w:133, season:3, title:'Vieux carnet du papa retrouvé', type:'major', contact:'shen', status:'done', sceneId:'vieux_carnet_papa' },
  { w:134, season:3, title:'Wei : qu\'est-ce que t\'a appris le carnet ?', type:'empty', contact:'wei', status:'todo' },
  { w:135, season:3, title:'Lu Huan : projet européen confidentiel', type:'empty', contact:'lu_huan', status:'todo' },
  { w:136, season:3, title:'Amanda : information à monnayer', type:'empty', contact:'amanda', status:'todo' },
  { w:137, season:3, title:'Inconnu : Mingzhe', type:'chitchat', contact:'inconnu', status:'todo', note:'Skinner' },
  { w:138, season:3, title:'Wei savait quelque chose', type:'major', contact:'wei', status:'done', sceneId:'wei_savait_quelque_chose' },
  { w:139, season:3, title:'Hugo : on prend une pause ?', type:'empty', contact:'hugo', status:'todo' },
  { w:140, season:3, title:'Tante Mei : courage ma puce', type:'chitchat', contact:'tante_mei', status:'todo' },
  { w:141, season:3, title:'Liu Wei : retour à NeoCity', type:'empty', contact:'liu_wei', status:'todo' },
  { w:142, season:3, title:'Lu Huan craque, premier moment humain', type:'major', contact:'lu_huan', status:'done', sceneId:'lu_huan_humain' },
  { w:143, season:3, title:'Maman : dis-moi tout', type:'empty', contact:'maman', status:'todo' },
  { w:144, season:3, title:'Pavillon Lu, dossier Hatsune découvert', type:'major', contact:'lu_huan', status:'done', sceneId:'pavillon_lu_revele' },
  { w:145, season:3, title:'Lin révélée = ta cousine', type:'major', contact:'lin', status:'done', sceneId:'lin_revele' },
  { w:146, season:3, title:'Wei : prends soin de toi', type:'chitchat', contact:'wei', status:'todo' },
  { w:147, season:3, title:'Lu Huan : silence radio', type:'empty', contact:'lu_huan', status:'todo' },
  { w:148, season:3, title:'Hugo te demande la vérité', type:'empty', contact:'hugo', status:'todo' },
  { w:149, season:3, title:'Tante Mei : prends ton temps', type:'chitchat', contact:'tante_mei', status:'todo' },
  { w:150, season:3, title:'Lin : on se voit demain ?', type:'chitchat', contact:'lin', status:'todo', note:'Skinner' },
  { w:151, season:3, title:'Amanda : invitation pour parler ?', type:'empty', contact:'amanda', status:'todo' },
  { w:152, season:3, title:'Première vraie rencontre IRL avec Lin', type:'empty', contact:'lin', status:'todo' },
  { w:153, season:3, title:'Maman : photo Tante Mei guérie', type:'chitchat', contact:'maman', status:'todo' },
  { w:154, season:3, title:'Lu Huan : tu veux qu\'on parle ?', type:'empty', contact:'lu_huan', status:'todo' },
  { w:155, season:3, title:'Inconnu : choisis ton camp', type:'chitchat', contact:'inconnu', status:'todo' },
  { w:156, season:3, title:'Réveillon A3 avec Lin', type:'cinematic', contact:'maman', status:'done', sceneId:'reveillon_a3' },
  { w:157, season:4, title:'Bonne année 2030', type:'chitchat', contact:'maman', status:'todo' },
  { w:158, season:4, title:'Wei : nouveau job ailleurs ?', type:'empty', contact:'wei', status:'todo' },
  { w:159, season:4, title:'Tante Mei : je veux te léguer le village', type:'empty', contact:'tante_mei', status:'todo' },
  { w:160, season:4, title:'Rumeurs fusion Lu/Hatsune', type:'major', contact:'amanda', status:'done', sceneId:'rumeurs_fusion_lu' },
  { w:161, season:4, title:'Hugo : on doit reparler de nous', type:'empty', contact:'hugo', status:'todo' },
  { w:162, season:4, title:'Lin : voilà ce que j\'ai trouvé', type:'empty', contact:'lin', status:'todo' },
  { w:163, season:4, title:'Dernière manche, 60 jours pour décider', type:'major', contact:'lu_huan', status:'done', sceneId:'derniere_manche' },
  { w:164, season:4, title:'Maman : journaliste demande à parler', type:'empty', contact:'maman', status:'todo' },
  { w:165, season:4, title:'Wei : témoin si besoin', type:'empty', contact:'wei', status:'todo' },
  { w:166, season:4, title:'Liu Wei : sois prudente', type:'chitchat', contact:'liu_wei', status:'todo' },
  { w:167, season:4, title:'Amanda essaie de revenir dans le jeu', type:'empty', contact:'amanda', status:'todo' },
  { w:168, season:4, title:'Lu Huan : board veut votre tête', type:'chitchat', contact:'lu_huan', status:'todo', note:'Skinner' },
  { w:169, season:4, title:'Tante Mei : photos des élèves de l\'école', type:'chitchat', contact:'tante_mei', status:'todo' },
  { w:170, season:4, title:'Hugo te quitte si mood < 4', type:'empty', contact:'hugo', status:'todo', note:'Conditionnel' },
  { w:171, season:4, title:'Lin : j\'ai besoin de plus de temps', type:'empty', contact:'lin', status:'todo' },
  { w:172, season:4, title:'Maman : tu rentres pour Pâques ?', type:'chitchat', contact:'maman', status:'todo' },
  { w:173, season:4, title:'Confrontation finale — Lin propose 4 voies', type:'major', contact:'lin', status:'done', sceneId:'confrontation_finale' },
  { w:174, season:4, title:'Wei : pas la peine, je suis avec toi', type:'empty', contact:'wei', status:'todo' },
  { w:175, season:4, title:'Lu Huan : un dernier dîner, peut-être ?', type:'empty', contact:'lu_huan', status:'todo' },
  { w:176, season:4, title:'Inconnu : ne te retourne pas', type:'chitchat', contact:'inconnu', status:'todo' },
  { w:177, season:4, title:'Tante Mei : armoire bleue est à toi désormais', type:'empty', contact:'tante_mei', status:'todo' },
  { w:178, season:4, title:'Mariage de Liu Wei au village', type:'empty', contact:'liu_wei', status:'todo' },
  { w:179, season:4, title:'Hugo : silence', type:'empty', contact:'hugo', status:'todo' },
  { w:180, season:4, title:'Amanda : information bonus', type:'empty', contact:'amanda', status:'todo' },
  { w:181, season:4, title:'Lin : on a un témoin', type:'empty', contact:'lin', status:'todo' },
  { w:182, season:4, title:'Maman propose de venir à NeoCity', type:'empty', contact:'maman', status:'todo' },
  { w:183, season:4, title:'Wei : appelle un avocat', type:'chitchat', contact:'wei', status:'todo' },
  { w:184, season:4, title:'Lu Huan : il faut qu\'on parle face à face', type:'empty', contact:'lu_huan', status:'todo' },
  { w:185, season:4, title:'Tante Mei : ton père aurait été fier', type:'chitchat', contact:'tante_mei', status:'todo' },
  { w:186, season:4, title:'Inconnu masqué : arrête tout', type:'chitchat', contact:'inconnu', status:'todo', note:'Skinner' },
  { w:187, season:4, title:'Hugo : photo d\'archive entre nous', type:'chitchat', contact:'hugo', status:'todo' },
  { w:188, season:4, title:'Soir tendu chez Lu Huan', type:'empty', contact:'lu_huan', status:'todo' },
  { w:189, season:4, title:'Lin : prête à témoigner', type:'empty', contact:'lin', status:'todo' },
  { w:190, season:4, title:'Monte la pression médias', type:'major', contact:'amanda', status:'done', sceneId:'monte_pression' },
  { w:191, season:4, title:'Wei : je serai là le jour J', type:'chitchat', contact:'wei', status:'todo' },
  { w:192, season:4, title:'Tante Mei : je viens à NeoCity', type:'empty', contact:'tante_mei', status:'todo' },
  { w:193, season:4, title:'Maman : je suis dans l\'avion', type:'empty', contact:'maman', status:'todo' },
  { w:194, season:4, title:'Hugo : je serai là si tu veux', type:'empty', contact:'hugo', status:'todo' },
  { w:195, season:4, title:'Décision intime nuit pavillon Lu', type:'empty', contact:'lu_huan', status:'todo' },
  { w:196, season:4, title:'Lin : tu choisis quoi ?', type:'empty', contact:'lin', status:'todo' },
  { w:197, season:4, title:'Maman : reviens, ma fille', type:'chitchat', contact:'maman', status:'todo', note:'Skinner' },
  { w:198, season:4, title:'Avant-dernier acte', type:'major', contact:'lu_huan', status:'done', sceneId:'avant_dernier_acte' },
  { w:199, season:4, title:'Wei : tu es prête ?', type:'chitchat', contact:'wei', status:'todo' },
  { w:200, season:4, title:'Inconnu : courage', type:'chitchat', contact:'inconnu', status:'todo' },
  { w:201, season:4, title:'Lu Huan : quoi qu\'il arrive', type:'chitchat', contact:'lu_huan', status:'todo' },
  { w:202, season:4, title:'Préparation finale (dossier, témoins)', type:'empty', contact:'shen', status:'todo' },
  { w:203, season:4, title:'Tante Mei : prie pour toi', type:'chitchat', contact:'tante_mei', status:'todo' },
  { w:204, season:4, title:'Hugo : embrasse-moi avant', type:'empty', contact:'hugo', status:'todo' },
  { w:205, season:4, title:'Imminence finale', type:'major', contact:'maman', status:'done', sceneId:'imminence_finale' },
  { w:206, season:4, title:'Lin : à demain', type:'chitchat', contact:'lin', status:'todo' },
  { w:207, season:4, title:'Maman : c\'est ton heure', type:'empty', contact:'maman', status:'todo' },
  { w:208, season:4, title:'Ending choisi → 1 des 4 fins', type:'cinematic', contact:'shen', status:'done', sceneId:'ending_choisi' }
];

const PHOTOS = [
  { id:'chat_selfie_arrivee_shen', file:'chat_selfie_arrivee_shen.jpeg', kind:'chat', season:1, weeks:[1], characters:['shen'], desc:'Selfie aéroport — arrivée Shen', status:'produced' },
  { id:'post_shen_train', file:'post_shen_train.png', kind:'post', season:1, weeks:[1], characters:['shen'], desc:'Post Insta arrivée train', status:'produced' },
  { id:'post_shen_depart', file:'post_shen_depart.png', kind:'post', season:1, weeks:[1], characters:['shen'], desc:'Post départ village', status:'produced' },
  { id:'chat_taxi_recu', file:'chat_taxi_recu.png', kind:'chat', season:1, weeks:[1,2], characters:['shen'], desc:'Reçu taxi première arrivée', status:'produced' },
  { id:'chat_badge_visiteur', file:'chat_badge_visiteur.jpeg', kind:'chat', season:1, weeks:[2], characters:['shen','wei'], desc:'Badge visiteur premier jour', status:'produced' },
  { id:'chat_wei_screenshot_badge', file:'chat_wei_screenshot_badge.png', kind:'chat', season:1, weeks:[2,7], characters:['wei'], desc:'Screenshot badge envoyé par Wei', status:'produced' },
  { id:'post_shen_studio', file:'post_shen_studio.png', kind:'post', season:1, weeks:[3], characters:['shen'], desc:'Post studio (W3 — tour du studio)', status:'produced' },
  { id:'chat_recu_loyer', file:'chat_recu_loyer.png', kind:'chat', season:1, weeks:[3,4], characters:['shen'], desc:'Reçu loyer (économie S1)', status:'produced' },
  { id:'chat_billets', file:'chat_billets.jpg', kind:'chat', season:1, weeks:[10,27], characters:['shen','maman'], desc:'Photo billets (économie / Tante Mei malade)', status:'produced' },
  { id:'chat_maman_plat', file:'chat_maman_plat.png', kind:'chat', season:1, weeks:[4,17,42], characters:['maman'], desc:'Photo plat de Maman (chitchat récurrent)', status:'produced' },
  { id:'post_maman_plat', file:'post_maman_plat.png', kind:'post', season:1, weeks:[17], characters:['maman'], desc:'Post Insta — plat Maman', status:'produced' },
  { id:'chat_tour_groupe_lu', file:'chat_tour_groupe_lu.jpg', kind:'chat', season:1, weeks:[12], characters:['lu_huan'], desc:'Tour Groupe Lu vue extérieure', status:'produced' },
  { id:'chat_lu_office_view', file:'chat_lu_office_view.png', kind:'chat', season:1, weeks:[12,30], characters:['lu_huan'], desc:'Bureau Lu, vue de l\'open space', status:'produced' },
  { id:'post_wei_tour', file:'post_wei_tour.png', kind:'post', season:1, weeks:[12], characters:['wei'], desc:'Post Wei devant la tour Lu', status:'produced' },
  { id:'post_wei_cafe', file:'post_wei_cafe.png', kind:'post', season:1, weeks:[15,19], characters:['wei'], desc:'Post Wei au café (vie sociale)', status:'produced' },
  { id:'chat_amanda_selfie_cafet', file:'chat_amanda_selfie_cafet.png', kind:'chat', season:1, weeks:[14,26], characters:['amanda'], desc:'Selfie Amanda à la cafétéria', status:'produced' },
  { id:'post_amanda_cadeau', file:'post_amanda_cadeau.png', kind:'post', season:1, weeks:[14], characters:['amanda'], desc:'Post Amanda — cadeau pour soi', status:'produced' },
  { id:'chat_shen_ascenseur_selfie', file:'chat_shen_ascenseur_selfie.png', kind:'chat', season:1, weeks:[40], characters:['shen','amanda'], desc:'Photo ascenseur — Le piège (W40)', status:'produced' },
  { id:'post_amanda_robe', file:'post_amanda_robe.png', kind:'post', season:2, weeks:[82,90], characters:['amanda'], desc:'Robe gala — soirée Lu', status:'produced' },
  { id:'post_lu_archi', file:'post_lu_archi.png', kind:'post', season:2, weeks:[63], characters:['lu_huan'], desc:'Post archi — lancement produit', status:'produced' },
  { id:'post_lu_nuit', file:'post_lu_nuit.png', kind:'post', season:2, weeks:[90], characters:['lu_huan'], desc:'Post Lu de nuit (gala)', status:'produced' },
  { id:'post_lu_portrait', file:'post_lu_portrait.png', kind:'post', season:2, weeks:[63,73], characters:['lu_huan'], desc:'Portrait Lu Huan officiel', status:'produced' },
  { id:'map_neocity', file:'map_neocity.jpg', kind:'map', season:1, weeks:[1,2], characters:[], desc:'Carte de NeoCity (app Maps)', status:'produced' },
  { id:'wallpaper_home', file:'wallpaper_home.png', kind:'wallpaper', season:1, weeks:[], characters:[], desc:'Wallpaper home (UI)', status:'produced' },
  { id:'wallpaper_home_dark', file:'wallpaper_home_dark.png', kind:'wallpaper', season:1, weeks:[], characters:[], desc:'Wallpaper home dark (UI)', status:'produced' },
  { id:'wallpaper_lock', file:'wallpaper_lock.jpeg', kind:'wallpaper', season:1, weeks:[], characters:[], desc:'Wallpaper lock screen (sakura)', status:'produced' },
  { id:'wallpaper_lock_dark', file:'wallpaper_lock_dark.png', kind:'wallpaper', season:1, weeks:[], characters:[], desc:'Wallpaper lock screen dark', status:'produced' },
  { id:'todo_w8_vieille_photo_papa', file:null, kind:'chat', season:1, weeks:[8], characters:['tante_mei','papa'], desc:'Vieille photo papa envoyée par Tante Mei (W8)', status:'todo' },
  { id:'todo_w22_hugo_hanami', file:null, kind:'chat', season:1, weeks:[22], characters:['hugo'], desc:'Café Hanami — rencontre Hugo', status:'todo' },
  { id:'todo_w23_hugo_croquis', file:null, kind:'chat', season:1, weeks:[23], characters:['hugo'], desc:'Croquis envoyé par Hugo', status:'todo' },
  { id:'todo_w24_chat_voisine', file:null, kind:'chat', season:1, weeks:[24], characters:['maman'], desc:'Chat de la voisine (Maman)', status:'todo' },
  { id:'todo_w33_hugo_peinture', file:null, kind:'chat', season:1, weeks:[33], characters:['hugo'], desc:'Peinture de Shen par Hugo', status:'todo' },
  { id:'todo_w35_armoire_bleue', file:null, kind:'chat', season:1, weeks:[35,120], characters:['inconnu','tante_mei'], desc:'Photo armoire bleue (mystère)', status:'todo' },
  { id:'todo_w37_couple_hugo', file:null, kind:'post', season:1, weeks:[37], characters:['shen','hugo'], desc:'Post couple Shen + Hugo', status:'todo' },
  { id:'todo_w39_colis_tante_mei', file:null, kind:'chat', season:1, weeks:[39,87], characters:['tante_mei'], desc:'Colis envoyé par Tante Mei', status:'todo' },
  { id:'todo_w47_liu_wei_arrive', file:null, kind:'chat', season:1, weeks:[47,48], characters:['liu_wei'], desc:'Liu Wei arrive du village + photos village', status:'todo' },
  { id:'todo_w50_grand_oeuvre', file:null, kind:'chat', season:1, weeks:[50], characters:['lu_huan','shen'], desc:'Salle comité — grand œuvre', status:'todo' },
  { id:'todo_w52_reveillon_a1', file:null, kind:'post', season:1, weeks:[52], characters:['maman','shen'], desc:'Réveillon A1 — table famille', status:'todo' },
  { id:'todo_w55_photo_papa_jeune', file:null, kind:'chat', season:2, weeks:[55,89], characters:['tante_mei','papa'], desc:'Photo papa jeune retrouvée', status:'todo' },
  { id:'todo_w57_galerie_hugo', file:null, kind:'post', season:2, weeks:[57], characters:['hugo'], desc:'Galerie Hugo — exposition', status:'todo' },
  { id:'todo_w63_lancement_produit', file:null, kind:'chat', season:2, weeks:[63,64], characters:['lu_huan'], desc:'Scène lancement produit (média)', status:'todo' },
  { id:'todo_w70_carnet_papa', file:null, kind:'chat', season:2, weeks:[70,78,133], characters:['shen','papa'], desc:'Carnet de notes du papa', status:'todo' },
  { id:'todo_w77_florence', file:null, kind:'post', season:2, weeks:[77,88], characters:['hugo','shen'], desc:'Florence — voyage Hugo', status:'todo' },
  { id:'todo_w83_bourse_tip', file:null, kind:'chat', season:2, weeks:[83], characters:['lu_huan'], desc:'Capture tuyau bourse (graphe)', status:'todo' },
  { id:'todo_w89_lin_enfant', file:null, kind:'chat', season:2, weeks:[89], characters:['maman','lin'], desc:'Photo Lin enfant', status:'todo' },
  { id:'todo_w90_gala_robe', file:null, kind:'post', season:2, weeks:[90], characters:['shen'], desc:'Shen au gala (robe pro)', status:'todo' },
  { id:'todo_w104_reveillon_a2', file:null, kind:'post', season:2, weeks:[104], characters:['maman','shen'], desc:'Réveillon A2', status:'todo' },
  { id:'todo_w118_mahjong', file:null, kind:'chat', season:3, weeks:[118], characters:['maman','tante_mei'], desc:'Mahjong au village', status:'todo' },
  { id:'todo_w123_registre_lu', file:null, kind:'chat', season:3, weeks:[123], characters:['inconnu'], desc:'Copie registre Lu Senior — passé révélé', status:'todo' },
  { id:'todo_w128_tante_mei_revele', file:null, kind:'chat', season:3, weeks:[128], characters:['tante_mei','papa'], desc:'Photo papa au Groupe Lu (révélation)', status:'todo' },
  { id:'todo_w144_dossier_hatsune', file:null, kind:'chat', season:3, weeks:[144], characters:['lu_huan'], desc:'Dossier Hatsune découvert pavillon Lu', status:'todo' },
  { id:'todo_w145_lin_irl', file:null, kind:'chat', season:3, weeks:[145,152], characters:['lin'], desc:'Lin révélée — première vraie photo', status:'todo' },
  { id:'todo_w153_tante_mei_guerie', file:null, kind:'chat', season:3, weeks:[153], characters:['tante_mei'], desc:'Tante Mei guérie (Maman envoie)', status:'todo' },
  { id:'todo_w156_reveillon_a3', file:null, kind:'post', season:3, weeks:[156], characters:['maman','lin','shen'], desc:'Réveillon A3 avec Lin', status:'todo' },
  { id:'todo_w160_fusion_lu_hatsune', file:null, kind:'post', season:4, weeks:[160], characters:['amanda','lu_huan'], desc:'Article fusion Lu/Hatsune (Insta media)', status:'todo' },
  { id:'todo_w169_eleves_ecole', file:null, kind:'chat', season:4, weeks:[169], characters:['tante_mei'], desc:'Photos élèves de l\'école au village', status:'todo' },
  { id:'todo_w173_confrontation', file:null, kind:'chat', season:4, weeks:[173], characters:['lin'], desc:'Confrontation finale — 4 voies', status:'todo' },
  { id:'todo_w177_armoire_bleue_legs', file:null, kind:'chat', season:4, weeks:[177], characters:['tante_mei'], desc:'Armoire bleue léguée à Shen', status:'todo' },
  { id:'todo_w178_mariage_liu_wei', file:null, kind:'post', season:4, weeks:[178], characters:['liu_wei'], desc:'Mariage Liu Wei au village', status:'todo' },
  { id:'todo_w187_archive_hugo', file:null, kind:'chat', season:4, weeks:[187], characters:['hugo','shen'], desc:'Photo d\'archive Hugo + Shen', status:'todo' },
  { id:'todo_w190_pression_medias', file:null, kind:'post', season:4, weeks:[190], characters:['amanda'], desc:'Capture article presse (pression)', status:'todo' },
  { id:'todo_w198_avant_dernier', file:null, kind:'chat', season:4, weeks:[198], characters:['lu_huan'], desc:'Avant-dernier acte — décor pavillon', status:'todo' },
  { id:'todo_w205_imminence', file:null, kind:'chat', season:4, weeks:[205], characters:['maman'], desc:'Imminence finale — message Maman', status:'todo' },
  { id:'todo_ending_justice', file:null, kind:'post', season:4, weeks:[208], characters:['shen'], desc:'⚖️ Ending Justice — procès médiatique', status:'todo' },
  { id:'todo_ending_argent', file:null, kind:'post', season:4, weeks:[208], characters:['shen'], desc:'💴 Ending Argent — fortune offshore', status:'todo' },
  { id:'todo_ending_vengeance', file:null, kind:'post', season:4, weeks:[208], characters:['shen'], desc:'🗡 Ending Vengeance — Groupe Lu démoli', status:'todo' },
  { id:'todo_ending_paix', file:null, kind:'post', season:4, weeks:[208], characters:['shen'], desc:'🌸 Ending Paix — école au village', status:'todo' }
];

const BATCHES = [
  { id:'B1', season:1, weeks:[3,5,6,8,9,10,11], theme:'Installation, premières habitudes, Maman/Wei' },
  { id:'B2', season:1, weeks:[13,15,17,19,20,21], theme:'Premier mois bureau, Amanda creuse, Maman tendre' },
  { id:'B3', season:1, weeks:[23,24,25,26,28,29], theme:'Hugo prend de la place, Lu Huan évalue' },
  { id:'B4', season:1, weeks:[31,32,33,36,37,38,39], theme:'Pression pro, ambiguïté Hugo, mystère armoire bleue' },
  { id:'B5', season:1, weeks:[41,42,43,44,45,46], theme:'Crise Amanda + Hugo en doute' },
  { id:'B6', season:1, weeks:[48,49,51], theme:'Liu Wei arrive, premier triangle, pre-Réveillon' }
];

const QUICK_STATUS = {
  scenes_total_target: 265,
  achievements: { target: 10, current: 10 },
  apps: { target: 11, current: 11 }
};

if (typeof module !== 'undefined') module.exports = { LORE, PERSONNAGES, TIMELINE, PHOTOS, BATCHES, QUICK_STATUS, RAW_BASE };
